### PR TITLE
fix(inspect): only pull required layers for inspecting OCI packages

### LINKED ISSUE #3572: Zarf package inspect unnecessarily pulls down package
### Environment
Device and OS:
N/A
App version:
0.48.1
Kubernetes distro being used:
N/A
Other:
Expected behavior observed in zarf version 0.32.2

### Steps to reproduce
1. Run zarf apckage inspect against a package stored in OCI For example:
`zarf package inspect oci://ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream` 

### Expected result
zarf displays the package config without downloading the entire package

### Actual Result
zarf pulls the entire package locally and then displays the pacakge config

### Visual Proof (screenshots, videos, text, etc)

Actual behavior:

Image

Note: The above screenshot shows 0.46.0, but i also tested against `0.48.1` and the behavior is the same. 

Expected behavior: 

Image

### Severity/Priority
Medium

### Additional Context
This is a regression from the expected behavior, which makes these commands far less usable as packages can be very large so getting the output of the command can take several minutes rather than a couple seconds. Unsure the exact zarf version where the behavior changed. The issue impacts all of the inspect commands including retrieving the sboms.

### PR DESCRIPTION
**Pull request by brandtkeller**
## Description

This Pull Request addresses the issue of attempting to Inspect packages in OCI and requiring the full OCI package to be downloaded before inspecting can progress. This is an issue as packages can be many gb's in size and inspecting the definition/images/manifests/sbom should not require the full package. 

At the same time, I didn't want to deviate the inspect logic too far from the `LoadPackage` process as this still applies for inspecting all other package sources. 

As a result these changes include:
- Remove `GetPackageFromSourceOrCluster`
  - Deduplicate use of `identifySource`
  - Enable `LoadPackage` to be used directly
- PullOCI now has PullOCIOptions
- Refactored `zoci.LayersFromRequestedComponents`
  - Split into `LayersFromComponents`  and `LayersFromImages` methods
- Create a new remote method `AssembleLayers`
  - This method becomes an explicit requirement as we now have a definition of the layers to be pulled
    - This is instead of the previous strategy where you might include layers or you might pull all
    - I'd wager this is more a more friendly SDK posture
  - This method now creates a map that tracks the layers that will be pulled for a zarf package
    - This allows both explicit tracking of layers being pulled
    - This also allows us to filter only required layers to pull (IE inspect operations)
- Refactored `PullPackage`
  - `LayersToPull` is now an explicit requirement instead of an implicit conditional
- Backwards compatibility support for deploy (not yet refactored)
- Constants for both packager2 layout and packager1 layout

## Related Issue

Fixes #3572 

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

**Comment by brandtkeller** [comment]
Testing for posterity:

## Definition
Zarf @ v0.53.0
```bash
zarf package inspect definition oci://ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream
2025-04-30 22:12:41 INF using config file location=/home/dev/work/zarf/zarf-config.toml
2025-04-30 22:12:44 INF Pulling ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream, size: 4.64 GBs
```

Zarf @ 3572_pull_refactor
```bash
./build/zarf package inspect definition oci://ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream
2025-04-30 22:11:41 INF using config file location=/home/dev/work/zarf/zarf-config.toml
2025-04-30 22:11:46 INF Pulling ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream, size: 21.86 KBs
```

## Images
Zarf @ v0.53.0
```bash
zarf package inspect images  oci://ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream
2025-04-30 22:14:41 INF using config file location=/home/dev/work/zarf/zarf-config.toml
2025-04-30 22:14:44 INF Pulling ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream, size: 4.64 GBs
```

Zarf @ 3572_pull_refactor
```bash
./build/zarf package inspect images  oci://ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream
2025-04-30 22:14:28 INF using config file location=/home/dev/work/zarf/zarf-config.toml
2025-04-30 22:14:31 INF Pulling ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream, size: 21.86 KBs
```

## SBOMs
Zarf @ v0.53.0
```bash
zarf package inspect sbom  oci://ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream
2025-04-30 22:17:11 INF using config file location=/home/dev/work/zarf/zarf-config.toml
2025-04-30 22:17:13 INF Pulling ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream, size: 4.64 GBs
```

Zarf @ 3572_pull_refactor
```bash
./build/zarf package inspect sbom  oci://ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream
2025-04-30 22:16:52 INF using config file location=/home/dev/work/zarf/zarf-config.toml
2025-04-30 22:16:55 INF Pulling ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream, size: 127.54 MBs
```

## Manifests
Zarf @ v0.53.0
```bash
zarf package inspect manifests  oci://ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream
2025-04-30 22:20:26 INF using config file location=/home/dev/work/zarf/zarf-config.toml
2025-04-30 22:20:31 INF Pulling ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream, size: 4.64 GBs
```

Zarf @ 3572_pull_refactor
```bash
./build/zarf package inspect manifests  oci://ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream
2025-04-30 22:19:46 INF using config file location=/home/dev/work/zarf/zarf-config.toml
2025-04-30 22:19:49 INF Pulling ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream, size: 685.41 KBs
```

## Values Files
Zarf @ v0.53.0
```bash
zarf package inspect values-files oci://ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream
2025-04-30 22:22:58 INF using config file location=/home/dev/work/zarf/zarf-config.toml
2025-04-30 22:23:01 INF Pulling ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream, size: 4.64 GBs
```

Zarf @ 3572_pull_refactor
```bash
./build/zarf package inspect values-files oci://ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream
2025-04-30 22:22:31 INF using config file location=/home/dev/work/zarf/zarf-config.toml
2025-04-30 22:22:35 INF Pulling ghcr.io/defenseunicorns/packages/uds/gitlab:17.9.1-uds.1-upstream, size: 685.41 KBs
```

File: src/internal/packager2/load.go [hunk 1]
```diff
@@ -107,82 +93,103 @@ func identifySource(src string) (string, error) {
 	if strings.Contains(src, ".part000") {
 		return "split", nil
 	}
+	// match deployed package names: lowercase, digits, hyphens
+	namePattern := regexp.MustCompile(`^[a-z0-9][a-z0-9\-]*$`)
```
Comment (AustinAbro321) [inline src/internal/packager2/load.go:97]: Would it cause a cyclical dependency to use `lint.IsLowercaseNumberHyphenNoStartHyphen` here? It's also generally preferred to run `regexp.MustCompile` as top level variables that way on the off chance they fail it'll be found immediately.

File: src/pkg/zoci/pull.go [hunk 2]
```diff
@@ -74,85 +50,159 @@ func (r *Remote) PullPackage(ctx context.Context, destinationDir string, concurr
 	return layersToPull, nil
 }
 
-// LayersFromRequestedComponents returns the descriptors for the given components from the root manifest.
-//
-// It also retrieves the descriptors for all image layers that are required by the components.
-func (r *Remote) LayersFromRequestedComponents(ctx context.Context, requestedComponents []v1alpha1.ZarfComponent) ([]ocispec.Descriptor, error) {
-	layers := make([]ocispec.Descriptor, 0)
+// AssembleLayers returns all layers for the given zarf package to pull from OCI.
+func (r *Remote) AssembleLayers(ctx context.Context, requestedComponents []v1alpha1.ZarfComponent, isSkeleton bool, inspectTarget string) ([]ocispec.Descriptor, error) {
```
Comment (AustinAbro321) [inline src/pkg/zoci/pull.go:54]: Won't block on it, but it is worth considering adding unit tests to to this function.

**Review by AustinAbro321 — CHANGES_REQUESTED** [review]
I think this will both be a positive refactor for the codebase, and a significant plus to users. Nice work so far

File: src/cmd/package.go [hunk 3]
```diff
@@ -664,23 +649,18 @@ func (o *packageInspectImagesOptions) run(cmd *cobra.Command, args []string) err
...
-	c, _ := cluster.New(ctx) //nolint:errcheck
+	inspectImageOpts := packager2.InspectPackageImagesOptions{
+		Architecture:            config.GetArch(),
+		Source:                  src,
+		SkipSignatureValidation: o.skipSignatureValidation,
+		PublicKeyPath:           pkgConfig.PkgOpts.PublicKeyPath,
+	}
 
-	pkg, err := packager2.GetPackageFromSourceOrCluster(ctx, c, src, o.skipSignatureValidation, pkgConfig.PkgOpts.PublicKeyPath)
+	result, err := packager2.InspectPackageImages(ctx, inspectImageOpts)
```
Comment (AustinAbro321) [inline src/cmd/package.go:659]: Not sure if this has been done in 100% of places (though it's worth checking), but we should have required fields like source as direct parameters instead of options

File: src/internal/packager2/load.go [hunk 4]
```diff
@@ -35,70 +36,55 @@ type LoadOptions struct {
...
 	srcType, err := identifySource(opt.Source)
 	if err != nil {
 		return nil, err
 	}
-	architecture := config.GetArch(opt.Architecture)
 
+	// Handle cluster-deployed packages directly
+	if srcType == "cluster" {
+		return loadFromCluster(ctx, opt.Source, opt.Cluster)
+	}
```
[the remark this answers is not in the document]
Comment (brandtkeller) [reply src/internal/packager2/load.go:53]: Thank you for bringing this back up - some of the idea gets lost in all the changes - but one of my thoughts (proposed) was that we might be capable of reconstructing the layout from the cluster at some point. 

That said - likely out of scope for this... but `getPackageFromSourceOrCluster` created a bottleneck that I didn't want to perpetuate. May be worth more research and putting `getFromSourceOrCluster` back for now...

File: src/internal/packager2/inspect.go [hunk 5]
```diff
@@ -305,6 +418,50 @@ func getTemplatedManifests(ctx context.Context, manifest v1alpha1.ZarfManifest,
 	return resources, nil
 }
 
+// loadInspectPackageLayout replicates the Load process while adding inspect targets not utilized in the primary LoadPackage function.
+func loadInspectPackageLayout(ctx context.Context, source, architecture string, inspectTarget InspectTarget, cluster *cluster.Cluster, filter filters.ComponentFilterStrategy, publicKeyPath string, skipSignatureValidation bool) (*layout.PackageLayout, error) {
```
Comment (AustinAbro321) [inline src/internal/packager2/inspect.go:422]: Thoughts on `LoadPackage` accepting an `InspectTarget` as an option? I believe this function is the same as `LoadPackage` besides that

File: src/internal/packager2/load.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (brandtkeller) [reply src/internal/packager2/load.go:53]: (Can't reply to your comment below - so I'll respond here"

My thought process behind trying to make cluster a first class source type was - because it _should_ be in zarf inspect operations. 

maybe we are not there yet - so I am not against keeping `getPackageFomSourceOrCluster` but I do want to start thinking about treating cluster as such and not performing `identifySource()` twice between this function and the `LoadPackage` itself while having cluster be a fallback source. 

Might be room to remove this from scope for now and revisit - as it is not strictly required to solve this point of refactor....

File: src/internal/packager2/inspect.go (hunk 5 above)
Comment (brandtkeller) [reply src/internal/packager2/inspect.go]: That was my original take - keeping `LoadPackage` as the sole-source for package load functionality. Feedback provided was to break `LoadPackage` into multiple private functions and then calling them from different public functions. 

Given the validation now is encapsulated by custom types and filter processes accordingly I am going to play with adding it back.

Comment (brandtkeller) [reply src/internal/packager2/inspect.go]: Updated

File: src/pkg/zoci/pull_test.go [hunk 6]
```diff
@@ -0,0 +1,100 @@
...
+
+			platform := oci.PlatformForArch(tc.opts.Architecture)
+			remote, err := zoci.NewRemote(ctx, packageRef, platform, oci.WithPlainHTTP(tc.opts.WithPlainHTTP))
+			require.NoError(t, err)
+
+			// get all layers
+			layers, err := remote.AssembleLayers(ctx, layoutExpected.Pkg.Components, false, zoci.AllLayers)
+			require.NoError(t, err)
+			t.Logf("Layers: %v", layers)
+			require.NotEmpty(t, layers)
```
[the remark this answers is not in the document]
Comment (brandtkeller) [reply src/pkg/zoci/pull_test.go:96]: Checking this now - the non-determinism of some of the layers on build is biting me but there should be other layers we can check.

File: src/pkg/zoci/pull_test.go [hunk 7]
```diff
@@ -0,0 +1,100 @@
...
+
+func TestAssembleLayers(t *testing.T) {
+	tt := []struct {
+		name string
+		path string
+		opts packager2.PublishPackageOpts
+	}{
+		{
+			name: "Publish package",
+			path: "../../internal/packager2/testdata/zarf-package-test-amd64-0.0.1.tar.zst",
```
[the remark this answers is not in the document]
Comment (brandtkeller) [reply src/pkg/zoci/pull_test.go]: great point - added test that creates a package prior to publish/assemble

File: src/internal/packager2/inspect.go [hunk 8]
```diff
@@ -18,19 +18,26 @@ import (
...
 
 const (
 	ManifestResource   ResourceType = "manifest"
 	ChartResource      ResourceType = "chart"
 	ValuesFileResource ResourceType = "valuesfile"
+
+	NoTarget         InspectTarget = ""
+	SbomTarget       InspectTarget = "sbom"
+	MetadataTarget   InspectTarget = "metadata"
+	ComponentsTarget InspectTarget = "components"
```
[the remark this answers is not in the document]
Comment (brandtkeller) [reply src/internal/packager2/inspect.go]: Agreed!

File: src/pkg/zoci/pull_test.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (brandtkeller) [reply src/pkg/zoci/pull_test.go:96]: Added more granular validation where possible.

File: src/internal/packager2/inspect.go [hunk 9]
```diff
@@ -257,6 +288,103 @@ func InspectDefinitionResources(ctx context.Context, packagePath string, opts In
...
+type InspectPackageDefinitionOptions struct {
+	Architecture            string
+	PublicKeyPath           string
+	SkipSignatureValidation bool
+}
+
+func InspectPackageDefinition(ctx context.Context, source string, opts InspectPackageDefinitionOptions) (InspectPackageDefinitionResult, error) {
+	cluster, _ := cluster.New(ctx) //nolint:errcheck
+
+	pkg, err := GetPackageFromSourceOrCluster(ctx, cluster, source, opts.SkipSignatureValidation, opts.PublicKeyPath)
```
Comment (AustinAbro321) [inline src/internal/packager2/inspect.go:343]: `GetPackageFromSourceOrCluster` should accept an inspect target

File: src/pkg/zoci/pull_test.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (AustinAbro321) [reply src/pkg/zoci/pull_test.go:96]: Makes sense, changes look good. I'd also recommend changing the require.NotEmpty field to require.Len

File: src/pkg/zoci/pull_test.go [hunk 10]
```diff
@@ -0,0 +1,127 @@
+// SPDX-License-Identifier: Apache-2.0
+// SPDX-FileCopyrightText: 2021-Present The Zarf Authors
+
+// Package zoci_test contains tests for interacting with Zarf packages stored in OCI registries.
+package zoci_test
```
Comment (AustinAbro321) [inline src/pkg/zoci/pull_test.go:5]: I did not know that was a thing in Go. Neat

File: src/internal/packager2/inspect.go [hunk 11]
```diff
@@ -18,19 +18,27 @@ import (
...
+	"github.com/zarf-dev/zarf/src/pkg/packager/filters"
 	"github.com/zarf-dev/zarf/src/pkg/state"
 	"github.com/zarf-dev/zarf/src/pkg/utils"
 	"github.com/zarf-dev/zarf/src/pkg/variables"
+	"github.com/zarf-dev/zarf/src/pkg/zoci"
 	"helm.sh/helm/v3/pkg/chartutil"
 )
 
 type ResourceType string
+type InspectTarget string
```
Comment (AustinAbro321) [inline src/internal/packager2/inspect.go:31]: While the type itself should probably change names, maybe LayerCategory (names are hard), I feel that this type should live in zoci. It helps the code articulate that these targets are only relevant when performing a pull from an OCI target.

**Review by AustinAbro321 — CHANGES_REQUESTED** [review]
A few more small notes. This is close

File: src/internal/packager2/inspect.go (hunk 11 above)
Comment (brandtkeller) [reply src/internal/packager2/inspect.go]: Agreed - I think i've iterated in a few circles where it makes sense for these to finally reconcile in the best location.

File: src/internal/packager2/load.go [hunk 12]
```diff
@@ -20,85 +20,73 @@ import (
...
+	"github.com/zarf-dev/zarf/src/pkg/lint"
 	"github.com/zarf-dev/zarf/src/pkg/packager/filters"
 	"github.com/zarf-dev/zarf/src/pkg/utils"
+	"github.com/zarf-dev/zarf/src/pkg/zoci"
 	"github.com/zarf-dev/zarf/src/types"
 )
 
 // LoadOptions are the options for LoadPackage.
 type LoadOptions struct {
+	Cluster                 *cluster.Cluster
```
Comment (AustinAbro321) [inline src/internal/packager2/load.go:32]: nit: this is not used

**Review by AustinAbro321 — APPROVED** [review]
