### PR TITLE
fix: docker containerd blob error

### LINKED ISSUE #2584: Zarf local docker fallback not working on MacOS+DockerDesktop+ContainerdMode
### Environment
Device and OS: M2 macbook pro
App version: have tried with both 0.33.0 and 0.34.0
Kubernetes distro being used: k3d v1.27.4+k3s1
Other: Docker Desktop with Containerd mode turned on

### Steps to reproduce
```shell
# Build an image locally, but DON'T push it. This tag does NOT exist in `registry.example.com`.
docker build -t registry.example.com/myimage:1.2.3 .

# Build the zarf package that references `registry.example.com/myimage:1.2.3` in the zarf.yaml
zarf package create --confirm --skip-sbom --no-progress

# Try to deploy it
zarf package deploy zarf-package-foo-arm64-1.2.3.tar.zst --confirm --no-progress -l debug
```

### Expected result
Package is deployed

### Actual Result
The package gets created just fine. As expected it says `Falling back to local 'docker' images, failed to find the manifest on a remote`. But it fails on deployment with this error:

image

If I decompress the zarf package and look at that `/images/blobs/sha256` folder, there indeed is not a file with that name.

image

The string `a02b607f0d337d98c48e812611a4289e8e10b81e5832685393292d83b059835c` DOES appear in the zarf package's `checksums.txt` file, next to a sha that DOES exist in the `images/blobs/sha256` folder.

In checksums.txt:
```
<snip>
a02b607f0d337d98c48e812611a4289e8e10b81e5832685393292d83b059835c images/blobs/sha256/ad69e88322c92fe909723f882c4c8213d412bbadfef687c7cf5e360adba141b6
<snip>
```

### Severity/Priority

I'd say medium? For the first time ever, I'm developing an application and a zarf package together. In the dev/test cycle, I 100% do not want to be building the docker image and pushing it to a registry just to be pulling it back down. I want to build the image locally, build the zarf package locally, and deploy to a local cluster.

### PR DESCRIPTION
**Pull request by AustinAbro321**
## Description

Fixes #2584 

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/.github/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/internal/packager/images/pull.go [hunk 1]
```diff
@@ -246,6 +246,32 @@ func Pull(ctx context.Context, cfg PullConfig) (map[transform.Image]v1.Image, er
...
+			return nil
+		}
+
+		hash, err := helpers.GetSHA256OfFile(path)
+		if err != nil {
+			return err
+		}
+		newFile := filepath.Join(blobDir, hash)
+
+		return os.Rename(path, newFile)
```
Comment (phillebaba) [inline src/internal/packager/images/pull.go:269]: Remove whitespace.

**Review by phillebaba — DISMISSED** [review]
Small NIT otherwise looks good.

File: src/internal/packager/images/pull.go [hunk 2]
```diff
@@ -246,6 +246,31 @@ func Pull(ctx context.Context, cfg PullConfig) (map[transform.Image]v1.Image, er
 	doneSaving <- nil
 	<-doneSaving
 
+	// Needed because when pulling form the local docker daemon, while using the docker containerd runtime
```
Comment (lucasrod16) [inline src/internal/packager/images/pull.go:249]: typo nit: should be `from` not `form`

**Review by lucasrod16 — DISMISSED** [review]

**Review by lucasrod16 — APPROVED** [review]
