### PR TITLE
fix: avoid incorrect cyclic error when two packages import each other on separate component chains

### LINKED ISSUE #3457: cyclic imports detection logic evaluates components that are not included in the package
### Environment
Zarf version: v0.48.0

It seems the package detection logic is evaluating every component in ./child-component/zarf.yaml regardless if ./zarf.yaml imports the component or not.

### Steps to reproduce
1. setup the following files/folder structsure:
```.
├── child-component
│   └── zarf.yaml
├── jq
│   └── zarf.yaml
└── zarf.yaml
```

zarf.yaml:
```yaml
---
kind: ZarfPackageConfig
metadata:
  name: example-package

components:
  # JQ
  - name: jq-amd64
    required: true
    import:
      path: jq

  - name: jq-darwin
    required: true
    import:
      path: jq

  - name: child-jq-command
    required: true
    import:
      path: child-component

  - name: jq-command    
    actions:
      onDeploy:
        defaults:
          mute: true
        before:
          - cmd: |
              echo "I'm doing something cool with JQ too!"
              echo "{}" | ./bin/jq
```

./jq/zarf.yaml:
```yaml
---
kind: ZarfPackageConfig
metadata:
  name: jq
  description: Deploys the jq bin to the ./bin directory for use with other packages.

components:
  - name: jq-amd64
    only:
      localOS: linux
    required: true
    description: Deploy ./bin/jq bin for use in other components
    files:
      - source: https://github.com/stedolan/jq/releases/latest/download/jq-linux64
        target: ./bin/jq
        executable: true
  - name: jq-darwin
    only:
      localOS: darwin
    required: true
    description: Deploy ./bin/jq bin for use in other components
    files:
      - source: https://github.com/stedolan/jq/releases/latest/download/jq-osx-amd64
        target: ./bin/jq
        executable: true
```

./child-component/zarf.yaml
```yaml
---
kind: ZarfPackageConfig
metadata:
  name: child-component

components:
  # JQ
  - name: jq-amd64
    required: true
    import:
      path: ../jq

  - name: jq-darwin
    required: true
    import:
      path: ../jq

  - name: child-jq-command
    actions:
      onDeploy:
        defaults:
          mute: true
        before:
          - cmd: |
              echo "I'm doing something cool with JQ"
              echo "{}" | ./bin/jq

  - name: jq-command
    required: true
    import:
      path: ../
```

2.  run `zarf package create`

### Expected result
Package successfully creates as the package does not import the any component twice.

### Actual Result
Package fails to create with the following error:
```
ERR failed to create package: package . imported in cycle by child-component in component jq-command
```

### Severity/Priority
High

I can't build packages anymore

### Additional Context
Add any other context or screenshots about the technical debt here.

### PR DESCRIPTION
**Pull request by AustinAbro321**
## Description

Fixes #3457

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/internal/packager2/layout/import.go [hunk 1]
```diff
@@ -23,7 +23,19 @@ import (
...
+		return component.Import.Name
+	}
+	return component.Name
+}
+
 func resolveImports(ctx context.Context, pkg v1alpha1.ZarfPackage, packagePath, arch, flavor string, importStack []string) (v1alpha1.ZarfPackage, error) {
+	// Zarf imports merge in the top level package objects variables and constants
+	// however, imports are defined at the component level.
+	// Two packages can both import one another as long as the importing components are on a different chains.
+	// To detect cyclic imports, the stack is checked to see if the package has already been imported on that chain.
```
Comment (mkcp) [inline src/internal/packager2/layout/import.go:37]: 👍

**Review by mkcp — APPROVED** [review]
Stepped through everything and LGTM 👍
