### PR TITLE
fix: truncate agent pod annotation so scheduler doesn't fail when annoation limit is exceeded

### LINKED ISSUE #3313: zarf.dev/original-image annotation can prevent pod scheduling
### Environment
Device and OS:
App version:
Kubernetes distro being used: EKS
Other:

### Steps to reproduce
1. Deploy a job that has a container name `sonarqube-sonarqube-change-default-admin-password` (manifest below)
### Expected result
Pod is scheduled into the cluster

### Actual Result
Scheduler errors with the following:
```
Warning  FailedCreate  48s    job-controller  (combined from similar events): Error creating: Pod "sonarqube-sonarqube-change-admin-password-hook-mqng2" is invalid: metadata.annotations: Invalid value: "zarf.dev/original-image-sonarqube-sonarqube-change-default-admin-password": name part must be no more than 63 characters
```

### Additional Context
Add any other context or screenshots about the technical debt here.

This is a job manifest deployed via bigbang:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  creationTimestamp: "2024-12-10T18:50:35Z"
  generation: 1
  labels:
    app: sonarqube
    helm.sh/chart: sonarqube-10.6.1-bb.2
    heritage: Helm
    release: sonarqube
  name: sonarqube-sonarqube-change-admin-password-hook
  namespace: sonarqube
  resourceVersion: "65755"
  uid: f53e435e-1a04-41f7-ae01-2361cfb6474f
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: f53e435e-1a04-41f7-ae01-2361cfb6474f
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sonarqube
        batch.kubernetes.io/controller-uid: f53e435e-1a04-41f7-ae01-2361cfb6474f
        batch.kubernetes.io/job-name: sonarqube-sonarqube-change-admin-password-hook
        controller-uid: f53e435e-1a04-41f7-ae01-2361cfb6474f
        heritage: Helm
        job-name: sonarqube-sonarqube-change-admin-password-hook
        release: sonarqube
      name: sonarqube-sonarqube-change-admin-password-hook
    spec:
      containers:
      - args:
        - |
          until curl -v --connect-timeout 100 sonarqube-sonarqube:9000/api/system/status | grep -w UP; do
            sleep 10
          done
          curl -v --connect-timeout 100 -u admin:admin -X POST "sonarqube-sonarqube:9000/api/users/change_password?login=admin&previousPassword=admin&password=someNewPassword"
          until curl -fsI http://localhost:15021/healthz/ready; do
            echo "Waiting for Istio sidecar proxy..."
            sleep 3
          done
          sleep 5
          echo "Stopping the istio proxy..."
          curl -X POST http://localhost:15020/quitquitquit
        command:
        - sh
        - -c
        env:
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: sonarqube-sonarqube-admin-password
        - name: CURRENT_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: currentPassword
              name: sonarqube-sonarqube-admin-password
        image: registry1.dso.mil/ironbank/big-bang/base:2.1.0
        imagePullPolicy: IfNotPresent
        name: sonarqube-sonarqube-change-default-admin-password
        resources:
          limits:
            cpu: "1"
            ephemeral-storage: 512G
            memory: 6144M
          requests:
            cpu: 10m
            ephemeral-storage: 1536M
            memory: 128Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: private-registry
      - name: private-registry
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: sonarqube-sonarqube
      serviceAccountName: sonarqube-sonarqube
      terminationGracePeriodSeconds: 30
```

### PR DESCRIPTION
**Pull request by AustinAbro321**
## Description

When the annotation name created by the agent is too long the scheduler errors. This fixes that by truncating the annotation name to be equal to the 63 character limit.

https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set

Fixes #3313 

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/internal/agent/hooks/pods.go [hunk 1]
```diff
@@ -42,8 +42,16 @@ func parsePod(object []byte) (*corev1.Pod, error) {
...
-	return fmt.Sprintf("%s/original-image-%s", annotationPrefix, containerName)
+func getImageAnnotationKey(ctx context.Context, containerName string) string {
+	annotationName := fmt.Sprintf("original-image-%s", containerName)
+	// Kubernetes requires all annotation names to be to be no more than 63 characters
+	// https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set
+	if len(annotationName) > 63 {
+		logger.From(ctx).Debug("truncating container name to fit Kubernetes 63 character annotation name limit", "container", containerName)
+		annotationName = annotationName[:63]
+	}
+	key := fmt.Sprintf("%s/%s", annotationPrefix, annotationName)
```
Comment (daniel-palmer-gu) [inline src/internal/agent/hooks/pods.go:53]: `key` is the value for the annotation and is the thing that should be truncated. Otherwise you end up with values that can be longer the 63 due to the `zarf.dev` `annotationPrefix` being added in

File: src/internal/agent/hooks/pods_test.go [hunk 2]
```diff
@@ -154,3 +154,27 @@ func TestPodMutationWebhook(t *testing.T) {
...
+		containerName string
+		expectedKey   string
+	}{
+		{
+			containerName: "nginx",
+			expectedKey:   "zarf.dev/original-image-nginx",
+		},
+		{
+			containerName: "a-very-long-container-name-that-exceeds-sixty-three-characters",
+			expectedKey:   "zarf.dev/original-image-a-very-long-container-name-that-exceeds-sixty-th",
```
Comment (daniel-palmer-gu) [inline src/internal/agent/hooks/pods_test.go:169]: note that this expected key is 72 characters long

Comment (daniel-palmer-gu) [reply src/internal/agent/hooks/pods_test.go:169]: we should be expecting 63 character maximum, right?

Comment (AustinAbro321) [reply src/internal/agent/hooks/pods_test.go:169]: Yeah that is expected. Read this https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set. Annotations keys are made of two segments. The name segment must be 63 characters or less. The prefix must be not longer than 253 characters.

Comment (daniel-palmer-gu) [reply src/internal/agent/hooks/pods_test.go:169]: Ah! Interesting that they separate the two.

File: src/internal/agent/hooks/pods.go (hunk 1 above)
Comment (daniel-palmer-gu) [reply src/internal/agent/hooks/pods.go:53]: Addressed from https://github.com/zarf-dev/zarf/pull/3314#discussion_r1878798130

File: src/test/packages/25-manifest-adoption/deployment.yaml [hunk 3]
```diff
@@ -23,7 +23,7 @@ spec:
         app: game
     spec:
       containers:
-        - name: multi-game
+        - name: "multi-game-long-name-to-test-agent-truncate-annotation-name"
```
Comment (AustinAbro321) [inline src/test/packages/25-manifest-adoption/deployment.yaml:26]: Went back and forth on whether I should add an e2e test. I decided a new e2e test would be heavy, but the pod unit tests won't enforce the 63 character rule without an actual cluster behind them, so I lengthened the name here, so we have a real test that the functionality is now working.

I made sure this test failed when run on main

Comment (mkcp) [reply src/test/packages/25-manifest-adoption/deployment.yaml:26]: Sounds good, coverage is valuable here and we can always delete later if we need

**Review by mkcp — DISMISSED** [review]
LGTM - nice turnaround on getting a tested fix ready for review

File: src/test/packages/25-manifest-adoption/deployment.yaml (hunk 3 above)
Comment (AustinAbro321) [reply src/test/packages/25-manifest-adoption/deployment.yaml]: Moving this to test 36, as the container name needs to be the same here otherwise the deployment won't get adopted correctly

**Review by phillebaba — APPROVED** [review]
LGTM :rose:
