### PR TITLE
fix: pulling not respecting "uncompressed" setting in metadata

### LINKED ISSUE #3464: `.metadata.uncompressed` is not being respected when pulled from OCI repo
### Environment
Device and OS: Linux
App version: v0.48.0
Kubernetes distro being used: n/a
Other: n/a

### Steps to reproduce
1. `zarf package pull oci://ghcr.io/a1994sc/zarf/k3s:1.31.5-k3s1`

### Expected result

- `zarf-package-k3s-amd64-1.31.5-k3s1.tar`

### Actual Result

- `zarf-package-k3s-amd64-1.31.5-k3s1.tar.zst`

### Visual Proof
- https://github.com/a1994sc/zarf-package-k3s

### Additional Context
See [`zarf.yaml`](https://github.com/a1994sc/zarf-package-k3s/blob/567813da82cc42b659f679038be1b244dc9958e7/zarf.yaml)

### PR DESCRIPTION
**Pull request by a1994sc**
## Description

Address `zarf package pull` not respecting `.metadata.uncompressed` package setting

## Related Issue

Fixes #3464

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/internal/packager2/pull.go [hunk 1]
```diff
@@ -84,6 +84,22 @@ func Pull(ctx context.Context, src, dir, shasum string, filter filters.Component
 	if err != nil && !errors.Is(err, os.ErrNotExist) {
 		return err
 	}
+	if strings.HasSuffix(name, ".tar") {
```
Comment (AustinAbro321) [inline src/internal/packager2/pull.go:87]: We want to avoid another unarchive and archive, as this can be quite costly depending on how big the package is, I've heard of 100+GB packages for example. Instead I believe this would be solved by changing the constant `.data.tar.zst` and the function `nameFromMetadata` depending on the value of .metadata.compressed

**Review by AustinAbro321 — CHANGES_REQUESTED** [review]

File: src/internal/packager2/pull.go (hunk 1 above)
Comment (a1994sc) [reply src/internal/packager2/pull.go:87]: I left some mental notes in the issue that I will bring over:

https://github.com/zarf-dev/zarf/issues/3464#issuecomment-2635484062

> [R]eviewing the code a bit, I think that it has something to do with:
> https://github.com/zarf-dev/zarf/blob/33d8a2a2dc84b89913cc74d45157a04f6230c5ec/src/internal/packager2/pull.go#L49
> though it does lead to a bit of a chicken and egg problem as we would need to determine the file extension by checking the `.metadata.uncompressed` but the code needs a local file to check...

So I guess is there a cleaner way to check the `zarf.yaml` of a remote artifact other then checking locally?

Comment (AustinAbro321) [reply src/internal/packager2/pull.go:87]: Ah gotcha, yeah packages published to https will already be compressed/uncompressed correctly, whereas oci packages are not compressed as the files comprising the packages are in oci layers. I would move the `nameFromMetadata` functions into `pullOCI` and `pullHTTP` and have these functions take in a directory rather than complete path then name / rename accordingly.

Comment (a1994sc) [reply src/internal/packager2/pull.go:87]: OK, I will give it a try over the weekend and see if that helps

Comment (a1994sc) [reply src/internal/packager2/pull.go:87]: hm, doing some thinking and should the updated function look something like this?

```golang
func pullOCI(ctx context.Context, src, tmpPath, shasum string, filter filters.ComponentFilterStrategy) (bool, string, error)
```

basically it still return the `isPartial` `bool` the `error` but adds a new `tarPath` `string`

File: src/internal/packager2/pull.go [hunk 2]
```diff
@@ -113,48 +113,52 @@ func pullOCI(ctx context.Context, src, tarPath, shasum string, filter filters.Co
...
-		return false, err
+		return false, "", err
 	}
 	err = archiver.Archive(allTheLayers, tarPath)
 	if err != nil {
-		return false, err
+		return false, "", err
 	}
-	return isPartial, nil
+	return isPartial, tarPath, nil
```
Comment (a1994sc) [inline src/internal/packager2/pull.go:161]: @AustinAbro321 does this look like a the direction that you wanted to go?

File: src/internal/packager2/pull.go (hunk 1 above)
Comment (a1994sc) [reply src/internal/packager2/pull.go]: I'm not sure it is the prettiest way to go about it, but I think that I added the logic needed to determine the file type with both `http(s)` and `oci` pulls

File: src/internal/packager2/pull.go (hunk 2 above)
Comment (AustinAbro321) [reply src/internal/packager2/pull.go:162]: Ah actually, I think you just need to move this block outside of `supportsFiltering`. 
```go
	pkg, err := remote.FetchZarfYAML(ctx)
	if err != nil {
		return false, "", err
	}
	if !pkg.Metadata.Uncompressed {
		tarPath = fmt.Sprintf("%s.zst", tarPath)
	}
```

Comment (a1994sc) [reply src/internal/packager2/pull.go:162]: OK, I should be able to have that update in the next little bit.

Comment (a1994sc) [reply src/internal/packager2/pull.go:162]: Updated the PR let me know of that works for you, thank you.

**Review by AustinAbro321 — DISMISSED** [review]
LGTM, nice work. Going to ask another member of my team to give it a look before merge

**Comment by a1994sc** [comment]
I will see if I can track down that windows test failing....

File: src/internal/packager2/pull.go [hunk 3]
```diff
@@ -113,87 +114,121 @@ func pullOCI(ctx context.Context, src, tarPath, shasum string, filter filters.Co
...
-		return err
+		return "", err
 	}
 	if received != shasum {
-		return fmt.Errorf("shasum mismatch for file %s, expected %s but got %s", tarPath, shasum, received)
+		return "", fmt.Errorf("shasum mismatch for file %s, expected %s but got %s", tarPath, shasum, received)
 	}
-	return nil
+
+	mtype, err := mimetype.DetectFile(tarPath)
```
Comment (AustinAbro321) [inline src/internal/packager2/pull.go:210]: Windows doesn't allow renaming of an already opened file. Rather than `defer f.close` you will have to run `f.close` anywhere after the `io.Copy`

Comment (a1994sc) [reply src/internal/packager2/pull.go:210]: gotcha... I will have an update to the function before this afternoon for the team to review

Comment (a1994sc) [reply src/internal/packager2/pull.go:216]: I moved the `f.Close()` to after 

```go
_, err = io.Copy(f, resp.Body)
```
and added `f.Close()` on error returns. Let me know if that helps

Comment (a1994sc) [reply src/internal/packager2/pull.go:216]: Gotcha, I will see if I can encapsulate that logic

Comment (a1994sc) [reply src/internal/packager2/pull.go:190]: Moved that logic to its own function, I believe that should address the windows issues.... _fingures crossed_

**Review by AustinAbro321 — DISMISSED** [review]
LGTM, nice work

**Comment by a1994sc** [comment]
Thank you!

File: src/internal/packager2/pull.go [hunk 4]
```diff
@@ -113,54 +114,104 @@ func pullOCI(ctx context.Context, src, tarPath, shasum string, filter filters.Co
...
+	return isPartial, tarPath, nil
 }
 
-func pullHTTP(ctx context.Context, src, tarPath, shasum string) error {
+func pullHTTP(ctx context.Context, src, tarDir, shasum string) (string, error) {
 	if shasum == "" {
-		return errors.New("shasum cannot be empty")
+		return "", errors.New("shasum cannot be empty")
+	}
+	tmpDir, err := utils.MakeTempDir(config.CommonOptions.TempDirectory)
```
Comment (brandtkeller) [inline src/internal/packager2/pull.go:169]: This `tmpDir` logic looks unused and redundant given that `tarDir` is a derivative of the same logic - can we remove this?

Comment (a1994sc) [reply src/internal/packager2/pull.go:169]: both `pullOCI` and `pullHTTP` destroy either temporary directories after they are done with their respective

```golang
defer os.Remove(tmpDir)
```

so we need to "copy" them to the `tmpDir` location so we don't try to reference a destroyed file.

Comment (AustinAbro321) [reply src/internal/packager2/pull.go:169]: I see the need for it in `pullOCI` since we need a place to store the individual layers before we archive them, but in `pullHTTP` we pull the binary down as is. It looks like only place `tmpDir` is used in `pullHTTP` is in `os.Remove`

Comment (a1994sc) [reply src/internal/packager2/pull.go:169]: Oh, I see... I'm very sorry, I thought that @brandtkeller was talking about it in the context of the greater `Pull` function.... Yes, I can see the unused and redundant `tmpDir`. Testing that it wasn't magically being used and will update the PR soon

Comment (a1994sc) [reply src/internal/packager2/pull.go]: Updated and the code works without that, thank you for the catch.

**Review by brandtkeller — APPROVED** [review]

**Review by AustinAbro321 — APPROVED** [review]
