### PR TITLE
fix: template variables and values in `.wait` actions

### LINKED ISSUE #4603: Zarf v0.71.1 wait.cluster no longer works with variables
### Environment
Device and OS: MAC OS Tahoe 26.2
App version: v0.71.1
Kubernetes distro being used: v1.33.4+rke2r1
Other: n/A

### Steps to reproduce
1. Stand up a cluster and zarf init
2. Create zarf package `zarf package create .` with this zarf.yaml:
```
kind: ZarfPackageConfig
metadata:
  name: test

variables:
- name: AGENT_TEST_VAR
  default: agent-hook

components:
  - name: test-123
    required: true
    actions:
      onDeploy:
        after:
          - description: Test using zarf variable
            wait:
              cluster:
                kind: pod
                name: "app=${ZARF_VAR_AGENT_TEST_VAR}"
                namespace: zarf
                condition: Ready
```
3. `zarf package deploy zarf-package-test-arm64.tar.zst --confirm`

### Expected result
zarf waits for pod's status (variable substitution works)

### Actual Result
zarf always fails for pod's status (variable substitution does not work). Output:

```
2026-02-12 09:00:08 INF starting deploy package=test
2026-02-12 09:00:08 INF deploying component name=test-123
2026-02-12 09:00:08 INF running wait action description=wait for pod/app=${ZARF_VAR_AGENT_TEST_VAR} to be Ready
2026-02-12 09:00:08 INF waiting for pod/ with label `app=${ZARF_VAR_AGENT_TEST_VAR}` in namespace zarf to exist.
2026-02-12 09:05:08 ERR failed to deploy package: unable to deploy component "test-123": unable to run component after action: wait timed out
```

### Visual Proof (screenshots, videos, text, etc)
See attached screenshot
Image

### Additional Context
Came about when upgrading zarf to `v0.71.1` and deploying uds-package-minio-operator (which has worked for a long time), but now this action fails https://github.com/uds-packages/minio-operator/blob/main/common/zarf.yaml#L63-L69

### PR DESCRIPTION
**Pull request by AustinAbro321**
## Description

Fixes #4603 which is a regression from #4549. In #4549, we no longer sent the command as a bash command, meaning environment variables of variables were not applied. Values templating was also no longer applied. 

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/test/e2e/30_component_action_cluster_test.go [hunk 1]
```diff
@@ -35,13 +35,13 @@ func TestComponentActionEdgeCases(t *testing.T) {
...
+	sourcePath := filepath.Join("src", "test", "packages", "30-component-actions-edgecases")
 	packageName := fmt.Sprintf("zarf-package-component-actions-edgecases-%s.tar.zst", e2e.Arch)
 	packagePath := filepath.Join(tmpdir, packageName)
 
-	stdOut, stdErr, err := e2e.Zarf(t, "package", "create", sourcePath, "--confirm", "-o", tmpdir)
+	stdOut, stdErr, err := e2e.Zarf(t, "package", "create", sourcePath, "--confirm", "-o", tmpdir, "--features=\"values=true\"")
 	require.NoError(t, err, stdOut, stdErr)
 
-	stdOut, stdErr, err = e2e.Zarf(t, "package", "deploy", packagePath, "--confirm")
+	stdOut, stdErr, err = e2e.Zarf(t, "package", "deploy", packagePath, "--confirm", "--features=\"values=true\"")
```
Comment (brandtkeller) [inline src/test/e2e/30_component_action_cluster_test.go]: nit: feature flag on deploy isn't required correct? 

```suggestion
	stdOut, stdErr, err = e2e.Zarf(t, "package", "deploy", packagePath, "--confirm")
```

**Review by brandtkeller — CHANGES_REQUESTED** [review]
Super minor nit - otherwise I am just running some additional tests.

**Comment by AustinAbro321** [comment]
Fixed some new lint errors in this PR also
