### PR TITLE
fix(tools,wait): add an http client with a timeout slightly shorter than waitInterval to wait.go

### LINKED ISSUE #4452: zarf tools wait-for http client does not have a configured
### Environment
First observed in github actions runners

### Steps to reproduce
1. Run `zarf tools wait-for` against an http server that does not respond.

### Expected result
Zarf will retry according to the configured waitInterval 

### Actual Result
Zarf hangs indefinitely until the process is cancelled or reaped.

### Visual Proof (screenshots, videos, text, etc)
Image
Timeout of 300s appears to be enforced by the containing runner. Upon testing this locally, wait-for will hang indefinitely on a server that accepts connections but isn't available to reply to the client.

### Severity/Priority
Moderate

### Additional Context
This is easily fixed by configuring a go http client with a timeout rather than using the default client without a timeout.

### PR DESCRIPTION
**Pull request by mkcp**
## Description
A user submitted this bug that appeared in CI. Initially it seemed that wait-for was only checking service health once, but looking through the code, it appears that the request will not timeout until the process is cancelled or reaped in some way. This PR adds an http client timeout similar to the waitInterval rather than prescribing a default.

## Related Issue
Fixes #4452 

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/pkg/utils/wait.go [hunk 1]
```diff
@@ -197,11 +203,12 @@ func waitForNetworkEndpoint(ctx context.Context, resource, name, condition strin
 				// Default to checking for a 2xx response.
 				if condition == "success" {
 					// Try to get the URL and check the status code.
-					resp, err := http.Get(url)
+					resp, err := httpClient.Get(url)
 					if err != nil {
 						l.Debug(err.Error())
 						continue
 					}
+					resp.Body.Close()
```
Comment (mkcp) [inline src/pkg/utils/wait.go]: Defer in loops _can_ but don't necessarily always leak resources. In order to avoid stacking up a bunch of open request bodies until the end of the loop, I opted to close the response body immediately. This is to avoid degenerate cases where a short waitInterval combined with a long timeout keep a bunch of unnecessary memory allocated. How much memory I'm not sure.

File: src/pkg/utils/wait.go [hunk 2]
```diff
@@ -197,11 +203,15 @@ func waitForNetworkEndpoint(ctx context.Context, resource, name, condition strin
 				// Default to checking for a 2xx response.
 				if condition == "success" {
 					// Try to get the URL and check the status code.
-					resp, err := http.Get(url)
+					resp, err := httpClient.Get(url)
```
Comment (brandtkeller) [inline src/pkg/utils/wait.go:206]: nit: Non-blocking - the only other outlier I see is context. I think respecting context would augment this strategy well here.

Comment (mkcp) [reply src/pkg/utils/wait.go:206]: This is a good idea that we should do but will change enough in how this code is arranged that I'd want to scope it out as a follow up. I'll write up an issue for it.

Comment (mkcp) [reply src/pkg/utils/wait.go:206]: https://github.com/zarf-dev/zarf/issues/4458
