### PR TITLE
fix: wait shell escaping

### LINKED ISSUE #3844: Zarf tools wait-for unable to use SELECTOR - always returns true
### Environment
Device and OS: MacOS 15.4.1
App version: v0.55.4
Kubernetes distro being used: v1.30.3+rke2r1
Other:

### Steps to reproduce
1.  Run `zarf tools wait-for pod -n kube-system kube-proxy-<node/hash>` (using pod NAME)
2. Observe zarf correctly waits for `pod/kube-proxy-<node/hash>`
3. Run `zarf tools wait-for pod -n kube-system component=kube-proxy` (using pod SELECTOR)
4. Observe zarf waits for `pod/ with label `component=kube-proxy`. This appears to be working but it is not actually waiting on the correct resource. 
5. To prove this assumption, run `zarf tools wait-for pod -n kube-system component=this-label-does-not-exist`
6. Observe zarf waits for `pod/ with label `component=this-label-does-not-exist` and returns a successful return code (in that zarf believes this pod with the label exists, but it does not). 

According to zarf, the `wait-for` command's usage should allow a SELECTOR in place of a NAME

```
$ zarf tools wait-for --help
By default Zarf will wait for all Kubernetes resources to be ready before completion of a component during a deployment.
This command can be used to wait for a Kubernetes resources to exist and be ready that may be created by a Gitops tool or a Kubernetes operator.
You can also wait for arbitrary network endpoints using REST or TCP checks.

Usage:
  zarf tools wait-for { KIND | PROTOCOL } { NAME | SELECTOR | URI } { CONDITION | HTTP_CODE } [flags]
```
NOTE: this bug is present on all k8s resources (deployments, daemonsets, statefulsets, etc.) anytime a SELECTOR is used.

### Expected result
Zarf correctly waits-for resources. If the resource doesn't exist, zarf correctly returns a non-zero return code.

### Actual Result
Zarf **always** return success (return code of 0) when using a SELECTOR.

### Visual Proof (screenshots, videos, text, etc)
See attached screenshot of all 3 commands, and the --help / usage of zarf tools wait-for

### Severity/Priority
Medium/Low

### Additional Context
Add any other context or screenshots about the technical debt here.

### PR DESCRIPTION
**Pull request by vincent-onebrief**
## Description

Currently when waiting for a jsonpath expression with bash special characters, the args passed to `kubectl wait` aren't properly escaped.

```console
$ zarf tools wait-for -n onebrief clusters cnpg-postgresql \
    '{.status.conditions[?(@.type=="Ready")].status}=True' \
    -l debug \
    --timeout 3s
DBG logger successfully initialized cfg.level=debug cfg.format=console cfg.destination=os.Stderr cfg.color=true
DBG User-configured features: features=
INF using config file location=zarf-config.yaml
DBG using temporary directory tmpDir=
INF waiting for clusters/cnpg-postgresql in namespace onebrief to exist.
DBG checking resource existence namespace=-n onebrief kind=clusters identifier=cnpg-postgresql
DBG cmd done cmd=[-e -c zarf tools kubectl get -n onebrief clusters cnpg-postgresql] stdout=NAME              AGE   INSTANCES   READY   STATUS                     PRIMARY
cnpg-postgresql   26h   1           1       Cluster in healthy state   cnpg-postgresql-1
 stderr= error=<nil>
INF waiting for clusters/cnpg-postgresql in namespace onebrief to be {.status.conditions[?(@.type=="Ready")].status}=True.
DBG wait error error=exit status 2
DBG checking resource existence namespace=-n onebrief kind=clusters identifier=cnpg-postgresql
DBG cmd done cmd=[-e -c zarf tools kubectl get -n onebrief clusters cnpg-postgresql] stdout=NAME              AGE   INSTANCES   READY   STATUS                     PRIMARY
cnpg-postgresql   26h   1           1       Cluster in healthy state   cnpg-postgresql-1
 stderr= error=<nil>
INF waiting for clusters/cnpg-postgresql in namespace onebrief to be {.status.conditions[?(@.type=="Ready")].status}=True.
DBG wait error error=exit status 2
ERR wait timed out
```

The same `kubectl wait` succeeds without issue

```console
$ kubectl wait -n onebrief \
  clusters cnpg-postgresql \
  --for jsonpath='{.status.conditions[?(@.type=="Ready")].status}=True' \
  --timeout=5s
cluster.postgresql.cnpg.io/cnpg-postgresql condition met
```

This is due to

```log
DBG wait done cmd=[-e -c build/zarf-mac-apple tools kubectl wait -n onebrief clusters cnpg-postgresql --for jsonpath={.status.conditions[?(@.type=="Ready")].status}=True --timeout=5s] stdout= stderr=sh: -c: line 0: syntax error near unexpected token `(' error=exit status 2
DBG wait error error=exit status 2
```

## Related Issue

Fixes #3844

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

**Comment by vincent-onebrief** [comment]
I didn't find any tests related to `wait-for` and the actual CLI calls that get made

File: src/pkg/utils/wait.go [hunk 1]
```diff
@@ -45,6 +46,8 @@ func ExecuteWait(ctx context.Context, waitTimeout, waitNamespace, condition, kin
 	// Check if waitType is JSONPath or condition
 	if isJSONPathWaitType(condition) {
 		waitType = "jsonpath="
+		// Ensure any conditions aren't shell escaped
+		condition = shellescape.Quote(condition)
```
Comment (AustinAbro321) [inline src/pkg/utils/wait.go]: Rather than adding another dependency, we should copy this function into Zarf. Seems like it's small enough to simply copy into this package. https://github.com/alessio/shellescape/blob/b09271781b1a504d1b88e5b44a28e8159b2efd74/shellescape.go#L30-L42

File: src/pkg/utils/wait.go [hunk 2]
```diff
@@ -29,6 +30,20 @@ func isJSONPathWaitType(condition string) bool {
 	return true
 }
 
+var shellRegex = regexp.MustCompile(`[^\w@%+=:,./-]`)
+
+func ShellQuote(s string) string {
```
Comment (AustinAbro321) [inline src/pkg/utils/wait.go]: We should make this function private

File: src/pkg/utils/wait.go [hunk 3]
```diff
@@ -29,6 +30,20 @@ func isJSONPathWaitType(condition string) bool {
 	return true
 }
 
+var shellRegex = regexp.MustCompile(`[^\w@%+=:,./-]`)
```
Comment (AustinAbro321) [inline src/pkg/utils/wait.go]:
```suggestion
// unsafeShellCharsRegex matches any character that is NOT a letter, digit, underscore (/w) or shell safe special characters
var unsafeShellCharsRegex = regexp.MustCompile(`[^\w@%+=:,./-]`)
```
small comment so it's easier to see what the regex does

File: src/pkg/utils/wait.go [hunk 4]
```diff
@@ -128,7 +145,10 @@ func ExecuteWait(ctx context.Context, waitTimeout, waitNamespace, condition, kin
 				zarfCommand, namespaceFlag, kind, identifier, waitType, condition, waitTimeout)
 
 			// If there is an error, log it and try again.
-			if _, _, err := exec.Cmd(shell, append(shellArgs, zarfKubectlWait)...); err != nil {
+			waitCmd := append(shellArgs, zarfKubectlWait)
+			waitStdout, waitStderr, err := exec.Cmd(shell, waitCmd...)
+			l.Debug("wait done", "cmd", waitCmd, "stdout", waitStdout, "stderr", waitStderr, "error", err)
```
Comment (AustinAbro321) [inline src/pkg/utils/wait.go:154]:
```suggestion
			l.Debug("wait done", "cmd", waitCmd, "stdout", waitStdout, "stderr", waitStderr)
```
nit: we already print the error on the next line if it happens

File: src/pkg/utils/wait.go (hunk 2 above)
Comment (brandtkeller) [inline src/pkg/utils/wait.go]: Additionally something you could help us create a reference for here is code attribution. Not something we have an example for today but we have been discussing. 

I'd love to see a couple lines that attribute the copied code

```suggestion
// Source: https://github.com/alessio/shellescape/blob/v1.6.0/shellescape.go
// SPDX-License-Identifier: MIT
// Minor edits: add any edits here or remove line
func shellQuote(s string) string {
```

File: src/pkg/utils/wait.go (hunk 4 above)
Comment (vincent-onebrief) [reply src/pkg/utils/wait.go:154]: This matches the existing pattern for `zarfKubectlGet`

**Review by brandtkeller — APPROVED** [review]
This looks reasonable. We don't have much in the way of testing this for regressions currently but I won't block on that. Open to additional testing for anyone interested.
