### PR TITLE
fix: properly create push auth credentials when registry address includes a repo path 

### LINKED ISSUE #3915: Mirror Resources No Longer Authenticates with External GitLab Registry
### Environment
Device and OS: Ubuntu Linux
App version: Zarf `v0.56.0` (started with `v0.51.0`), GitLab `v17.10.3`
Kubernetes distro being used: RKE2 `v1.32.4+rke2r1`
Other:

### Steps to reproduce
1. Use `zarf pacakge mirror-resources` targeting a GitLab registry

### Expected result

Images from the package pushed to the GitLab registry. Example successful output using zarf `v0.50.0`:

### Actual Result

Starting with Zarf `v0.51.0`, this operation fails with 401 errors. Tested multiple versions up to the latest version `v0.56.0` with similar results

### Visual Proof (screenshots, videos, text, etc)

Successful with `v0.50.0`

```
$ ./zarf_v0.50.0_Linux_amd64 package mirror-resources zarf-package-gitlab-support-images-amd64-0.3.0.tar.zst \
    --registry-url registry.iversen.disco-stg.bsf.tools/bsf-images \
    --registry-push-username "zarf-user" \
    --registry-push-password "${GITLAB_API_TOKEN}" \
    --retries 0 \
    --tmpdir ./tmp \
    --confirm \
    -l trace
2025-06-16 08:19:20 DBG logger successfully initialized cfg.level=debug cfg.format=console cfg.destination=os.Stderr cfg.color=true
2025-06-16 08:19:21 INF pushing image name=registry.iversen.disco-stg.bsf.tools/bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v17.10.1-zarf-2339378743
2025-06-16 08:19:21 INF pushing image name=registry.iversen.disco-stg.bsf.tools/bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v17.10.1
2025-06-16 08:19:21 INF pushing image name=registry.iversen.disco-stg.bsf.tools/bsf-images/library/ubuntu:22.04-zarf-4208865063
2025-06-16 08:19:22 INF pushing image name=registry.iversen.disco-stg.bsf.tools/bsf-images/library/ubuntu:22.04
```

Failure with `v0.51.0`

```
$ ./zarf_v0.51.0_Linux_amd64 package mirror-resources zarf-package-gitlab-support-images-amd64-0.3.0.tar.zst \
    --registry-url registry.iversen.disco-stg.bsf.tools/bsf-images \
    --registry-push-username "zarf-user" \
    --registry-push-password "${GITLAB_API_TOKEN}" \
    --retries 0 \
    --tmpdir ./tmp \
    --confirm \
    -l trace
2025-06-16 08:19:28 DBG logger successfully initialized cfg.level=debug cfg.format=console cfg.destination=os.Stderr cfg.color=true
2025-06-16 08:19:29 INF pushing image name=registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v17.10.1
2025-06-16 08:19:29 ERR failed to mirror images: failed to push image registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v17.10.1: PUT "https://registry.iversen.disco-stg.bsf.tools/v2/bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper/manifests/x86_64-v17.10.1-zarf-2339378743": response status code 401: unauthorized: authentication required: [map[Action:pull Class: Name:bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper ProjectPath: Type:repository] map[Action:push Class: Name:bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper ProjectPath: Type:repository]]
```

Failure with `v0.56.0`

```
$ ./zarf_v0.56.0_Linux_amd64 package mirror-resources zarf-package-gitlab-support-images-amd64-0.3.0.tar.zst \
    --registry-url registry.iversen.disco-stg.bsf.tools/bsf-images \
    --registry-push-username "zarf-user" \
    --registry-push-password "${GITLAB_API_TOKEN}" \
    --retries 0 \
    --tmpdir ./tmp \
    --confirm \
    -l trace
2025-06-16 08:33:28 DBG logger successfully initialized cfg.level=debug cfg.format=console cfg.destination=os.Stderr cfg.color=true
2025-06-16 08:33:28 DBG using temporary directory tmpDir=./tmp
2025-06-16 08:33:29 DBG package contains images and repos images=2 repos=0
2025-06-16 08:33:29 INF mirroring images images=2
2025-06-16 08:33:29 INF pushing image name=registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v17.10.1
2025-06-16 08:33:29 DBG retrying image push error=failed to push image registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v17.10.1: failed to perform "PushReference" on destination: PUT "https://registry.iversen.disco-stg.bsf.tools/v2/bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper/manifests/x86_64-v17.10.1-zarf-2339378743": response status code 401: unauthorized: authentication required: [map[Action:pull Class: Name:bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper ProjectPath: Type:repository] map[Action:push Class: Name:bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper ProjectPath: Type:repository]] concurrency=1
2025-06-16 08:33:30 DBG retrying image push error=failed to push image registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v17.10.1: failed to perform "PushReference" on destination: PUT "https://registry.iversen.disco-stg.bsf.tools/v2/bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper/manifests/x86_64-v17.10.1-zarf-2339378743": response status code 401: unauthorized: authentication required: [map[Action:pull Class: Name:bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper ProjectPath: Type:repository] map[Action:push Class: Name:bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper ProjectPath: Type:repository]] concurrency=1
2025-06-16 08:33:30 DBG retrying component image(s) push response_timeout=10s
2025-06-16 08:33:32 INF pushing image name=registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v17.10.1
2025-06-16 08:33:32 DBG retrying image push error=failed to push image registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v17.10.1: failed to perform "PushReference" on destination: PUT "https://registry.iversen.disco-stg.bsf.tools/v2/bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper/manifests/x86_64-v17.10.1-zarf-2339378743": response status code 401: unauthorized: authentication required: [map[Action:pull Class: Name:bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper ProjectPath: Type:repository] map[Action:push Class: Name:bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper ProjectPath: Type:repository]] concurrency=1
2025-06-16 08:33:33 DBG retrying image push error=failed to push image registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v17.10.1: failed to perform "PushReference" on destination: PUT "https://registry.iversen.disco-stg.bsf.tools/v2/bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper/manifests/x86_64-v17.10.1-zarf-2339378743": response status code 401: unauthorized: authentication required: [map[Action:pull Class: Name:bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper ProjectPath: Type:repository] map[Action:push Class: Name:bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper ProjectPath: Type:repository]] concurrency=1
2025-06-16 08:33:33 DBG retrying component image(s) push response_timeout=1m0s
2025-06-16 08:33:35 INF pushing image name=docker.io/library/ubuntu:22.04
2025-06-16 08:33:35 DBG retrying image push error=failed to push image docker.io/library/ubuntu:22.04: failed to perform "PushReference" on destination: PUT "https://registry.iversen.disco-stg.bsf.tools/v2/bsf-images/library/ubuntu/manifests/22.04-zarf-4208865063": response status code 401: unauthorized: authentication required: [map[Action:pull Class: Name:bsf-images/library/ubuntu ProjectPath: Type:repository] map[Action:push Class: Name:bsf-images/library/ubuntu ProjectPath: Type:repository]] concurrency=1
2025-06-16 08:33:36 DBG retrying image push error=failed to push image docker.io/library/ubuntu:22.04: failed to perform "PushReference" on destination: PUT "https://registry.iversen.disco-stg.bsf.tools/v2/bsf-images/library/ubuntu/manifests/22.04-zarf-4208865063": response status code 401: unauthorized: authentication required: [map[Action:pull Class: Name:bsf-images/library/ubuntu ProjectPath: Type:repository] map[Action:push Class: Name:bsf-images/library/ubuntu ProjectPath: Type:repository]] concurrency=1
2025-06-16 08:33:36 DBG retrying component image(s) push response_timeout=1m0s
2025-06-16 08:33:36 ERR failed to push images: All attempts fail:
#1: All attempts fail:
#1: failed to push image registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v17.10.1: failed to perform "PushReference" on destination: PUT "https://registry.iversen.disco-stg.bsf.tools/v2/bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper/manifests/x86_64-v17.10.1-zarf-2339378743": response status code 401: unauthorized: authentication required: [map[Action:pull Class: Name:bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper ProjectPath: Type:repository] map[Action:push Class: Name:bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper ProjectPath: Type:repository]]
#2: failed to push image registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v17.10.1: failed to perform "PushReference" on destination: PUT "https://registry.iversen.disco-stg.bsf.tools/v2/bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper/manifests/x86_64-v17.10.1-zarf-2339378743": response status code 401: unauthorized: authentication required: [map[Action:pull Class: Name:bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper ProjectPath: Type:repository] map[Action:push Class: Name:bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper ProjectPath: Type:repository]]
#2: All attempts fail:
#1: failed to push image registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v17.10.1: failed to perform "PushReference" on destination: PUT "https://registry.iversen.disco-stg.bsf.tools/v2/bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper/manifests/x86_64-v17.10.1-zarf-2339378743": response status code 401: unauthorized: authentication required: [map[Action:pull Class: Name:bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper ProjectPath: Type:repository] map[Action:push Class: Name:bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper ProjectPath: Type:repository]]
#2: failed to push image registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v17.10.1: failed to perform "PushReference" on destination: PUT "https://registry.iversen.disco-stg.bsf.tools/v2/bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper/manifests/x86_64-v17.10.1-zarf-2339378743": response status code 401: unauthorized: authentication required: [map[Action:pull Class: Name:bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper ProjectPath: Type:repository] map[Action:push Class: Name:bsf-images/gitlab-org/gitlab-runner/gitlab-runner-helper ProjectPath: Type:repository]]
#3: All attempts fail:
#1: failed to push image docker.io/library/ubuntu:22.04: failed to perform "PushReference" on destination: PUT "https://registry.iversen.disco-stg.bsf.tools/v2/bsf-images/library/ubuntu/manifests/22.04-zarf-4208865063": response status code 401: unauthorized: authentication required: [map[Action:pull Class: Name:bsf-images/library/ubuntu ProjectPath: Type:repository] map[Action:push Class: Name:bsf-images/library/ubuntu ProjectPath: Type:repository]]
#2: failed to push image docker.io/library/ubuntu:22.04: failed to perform "PushReference" on destination: PUT "https://registry.iversen.disco-stg.bsf.tools/v2/bsf-images/library/ubuntu/manifests/22.04-zarf-4208865063": response status code 401: unauthorized: authentication required: [map[Action:pull Class: Name:bsf-images/library/ubuntu ProjectPath: Type:repository] map[Action:push Class: Name:bsf-images/library/ubuntu ProjectPath: Type:repository]]
```

### Additional Context
Add any other context or screenshots about the technical debt here.

### PR DESCRIPTION
**Pull request by AustinAbro321**
## Description

We were allowing users to give a path to oras auth that looks like `registry.com/my-namespace`, but when you give anything more than the host to the oras auth client it breaks. 

## Related Issue

Fixes #3915 

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/internal/packager/images/push.go [hunk 1]
```diff
@@ -232,3 +243,15 @@ func copyImage(ctx context.Context, src *oci.Store, remote oras.Target, srcName
 	}
 	return nil
 }
+
+// parse registry reference returns a registry.Reference with only the host if the registry URL only contains a host
+// otherwise calls registry.ParseReference()
+func parseRegistryReference(registryURL string) (registry.Reference, error) {
```
Comment (mkcp) [inline src/internal/packager/images/push.go:249]: 👍

**Review by mkcp — APPROVED** [review]
LGTM
