### PR TITLE
fix: update creds not breaking when internal git server not deployed

### LINKED ISSUE #2903: Zarf tools update-creds errors when updating internal git or artifact server when it doesn't exist
### Environment
App version: v0.38.2 (though the issue may have been introduced earlier)

### Steps to reproduce
1. zarf init --confirm (no git server deployed)
2. zarf tools update-creds

### Expected result
Update creds successfully

### Actual Result
Fails because Zarf tries to login to the git server to generate a new artifact token, but the git server doesn't exist. 

### Temporary workaround
Update creds one at a time. For example if you only need to update the registry creds and the state in the agent run
```bash
zarf tools update-creds registry
zarf tools update-creds agent
```

### Note
The underlying issue here is that we save state for git servers and artifact servers even when they don't exist, but we should create a fix for this in the short term. This is related to #2740

### PR DESCRIPTION
**Pull request by AustinAbro321**
## Description

This PR fixes a bug where Zarf will error when the git server or artifact server doesn't exist and `zarf tools update-creds` is run

## Related Issue

Fixes #2903 

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/cmd/tools/zarf.go [hunk 1]
```diff
@@ -155,31 +155,17 @@ var updateCredsCmd = &cobra.Command{
...
-						return err
-					}
-					newState.ArtifactServer.PushToken = tokenSha1
-					return nil
-				})
-				if err != nil {
-					// Warn if we couldn't actually update the git server (it might not be installed and we should try to continue)
-					message.Warnf(lang.CmdToolsUpdateCredsUnableCreateToken, err.Error())
+				if kerrors.IsNotFound(err) {
+					message.Warn(updateErr.Error())
```
Comment (schristoff) [inline src/cmd/tools/zarf.go:166]: can we return errs as errs plz :)

File: src/cmd/tools/zarf.go [hunk 2]
```diff
@@ -155,31 +155,17 @@ var updateCredsCmd = &cobra.Command{
...
-					return err
-				}
-				_, err = tunnel.Connect(cmd.Context())
-				if err != nil {
-					return err
+				pushToken, err := c.UpdateInternalArtifactServerToken(ctx, oldState.GitServer)
+				updateErr := fmt.Errorf("unable to create the new Gitea artifact token: %w", err)
+				// TODO once Zarf is changed so the default state is empty for a service when it is not deployed
+				// and sufficient time has passed for users state to get updated we should error on isNotFound
+				if err != nil && !kerrors.IsNotFound(err) {
```
Comment (schristoff) [inline src/cmd/tools/zarf.go:162]: > Check if err 
If err 
>>  Check if is not found 
return  not found 
> return `newState.ArtifactServer.PushToken = pushToken` , no else

Comment (AustinAbro321) [reply src/cmd/tools/zarf.go:162]: I think the formatting got messed up here

File: src/cmd/tools/zarf.go (hunk 1 above)
Comment (AustinAbro321) [reply src/cmd/tools/zarf.go:166]: The point of this PR is to log a warning instead of an error when `kerrors.IsNotFound` is true since otherwise `zarf tools update-creds` fails every time.

An alternative I considered was to create a function `internalGitServerExists()` to use here instead of `isInternal()` which would avoid this block all together if it's not found. I ultimately went with this way, as I thought two functions might be confusing (though maybe that's okay since the reality is that it's confusing and we need to change how we create state)

Comment (schristoff) [reply src/cmd/tools/zarf.go:166]: okay, that makes sense. :)

File: src/cmd/tools/zarf.go (hunk 2 above)
Comment (schristoff) [reply src/cmd/tools/zarf.go:162]: fixed (hopefully that makes more sense)

Comment (AustinAbro321) [reply src/cmd/tools/zarf.go]: I wanted to not return the errors on `kerrors.IsNotFound` since some users might not have a git server deployed and in that case this function would always error. 

I just changed the code to not get to this block if the git server doesn't exist which hopefully clarifies intent

**Review by schristoff — APPROVED** [review]
