### PR TITLE
fix(publish): deterministic SHA for package publish

### LINKED ISSUE #3655: Package publish creates a new digest SHA for each publish
### Steps to reproduce
1. Login to a registry for publishing a zarf package
2. Create a package - IE `zarf package create examples/helm-charts`
3. Run `Zarf package publish ...`
4. Inspect the index and manifest digests for the package
5. Run `Zarf package publish ...`
6. Inspect the index and manifest digests for the package

### Expected result

No change to the digests

### Actual Result

Digests are changing

### PR DESCRIPTION
**Pull request by brandtkeller**
## Description

Resolves the publish behavior that currently results in the digests changing in each subsequent publish of the same pre-built package. 

Uses the build timestamp for the `created` ORAS annotation. Sorts the layers by digest to establish a deterministic order. 

## Related Issue

Fixes #3655

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/internal/packager2/layout/oci.go [hunk 1]
```diff
@@ -78,11 +80,28 @@ func (r *Remote) Push(ctx context.Context, pkgLayout *PackageLayout, concurrency
 		descs = append(descs, desc)
 	}
 
+	// Sort by Digest string
+	sort.Slice(descs, func(i, j int) bool {
```
Comment (mkcp) [inline src/internal/packager2/layout/oci.go:84]: Clean 👍

File: src/internal/packager2/layout/oci.go [hunk 2]
```diff
@@ -78,11 +80,28 @@ func (r *Remote) Push(ctx context.Context, pkgLayout *PackageLayout, concurrency
...
+		return descs[i].Digest < descs[j].Digest
+	})
+
 	annotations := annotationsFromMetadata(pkgLayout.Pkg.Metadata)
+
+	// Perform the conversion of the string timestamp to the appropriate format in order to maintain backwards compatibility
+
+	t, err := time.Parse(time.RFC1123Z, pkgLayout.Pkg.Build.Timestamp)
+	if err != nil {
+		// TODO: if we change the format of the timestamp, we need to update the conversion here
```
Comment (mkcp) [inline src/internal/packager2/layout/oci.go:94]: Good callout and error checking.

NIT: Let's extract the `time.RFC1123Z` as a pkg const like `OCITimeFormat` or sensible alternative. Then this TODO can be provided as a doccomment, e.g.
Screenshot 2025-04-10 at 15 54 08

File: src/internal/packager2/layout/oci.go [hunk 3]
```diff
@@ -78,11 +80,28 @@ func (r *Remote) Push(ctx context.Context, pkgLayout *PackageLayout, concurrency
...
+		// and also account for an error state for mismatch with older formats
+		return fmt.Errorf("unable to parse timestamp: %w", err)
+	}
+	annotations[ocispec.AnnotationCreated] = t.Format(time.RFC3339)
```
Comment (mkcp) [inline src/internal/packager2/layout/oci.go:98]: See nit above, extract `time.RFC3339` into a pkg const with a semantic name.

File: src/internal/packager2/publish_test.go [hunk 4]
```diff
@@ -245,6 +245,61 @@ func TestPublishPackage(t *testing.T) {
 	}
 }
 
+func TestPublishPackageDeterministic(t *testing.T) {
```
Comment (mkcp) [inline src/internal/packager2/publish_test.go:248]: Good test 👍

**Review by mkcp — COMMENTED** [review]
Good work, really excited for this!

**Review by mkcp — APPROVED** [review]
LGTM
