### PR TITLE
fix(deploy)!: override actions wait commands

### LINKED ISSUE #4388: bug: namespace override is not applied to component "wait" actions
### Environment
Device and OS: MacOS 26.1
App version: 0.66.0
Kubernetes distro being used: k3d v1.32.5+k3s1
Other:

### Steps to reproduce
1. Deploy zarf package using `-n` to override namespace with a `wait` action in the component

```
kind: ZarfPackageConfig
metadata:
  name: podinfo
  description: Install podinfo
  version: 6.7.0

variables:
  - name: REPLICAS
    default: '1'

components:
  - name: podinfo
    required: true
    charts:
      - name: podinfo
        version: 6.7.0
        namespace: podinfo
        # In this case `url` will load the helm chart located in the podinfo git repository
        url: https://github.com/stefanprodan/podinfo.git
        # By default git will look in the root of the git repository but you can define a sub directory with `gitPath`
        gitPath: charts/podinfo
        valuesFiles:
          - ./values.yaml
    images:
      - curlimages/curl:8.16.0
      - ghcr.io/stefanprodan/podinfo:6.7.0
      - ghcr.io/stefanprodan/podinfo:6.7.0
      - giantswarm/tiny-tools
      - stefanprodan/grpc_health_probe:v0.3.0
      # Cosign artifacts for images - helm-charts - demo-helm-charts
      - ghcr.io/stefanprodan/podinfo:sha256-57a654ace69ec02ba8973093b6a786faa15640575fbf0dbb603db55aca2ccec8.sig
    actions:
      onDeploy:
        before:
          - cmd: "sleep 3"
        after:
          - wait:
              cluster:
                kind: deployment
                name: podinfo
                namespace: podinfo
                condition: "{.status.readyReplicas}=${ZARF_VAR_REPLICAS}"
          - cmd: "sleep 3"

```

### Expected result
package should install in overriden namespace and wait should validate it exists

### Actual Result
package deploys in namespace but wait still looks for it in the namespace in the zarf.yaml not the override namespace

### Additional Context
Add any other context or screenshots about the technical debt here.

### PR DESCRIPTION
**Pull request by brandtkeller**
## Description

Currently namespace overrides only detects and/or modifies charts and manifests. This PR adds support for actions wait definitions.

## Related Issue

Fixes #4388

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/api/v1alpha1/package.go [hunk 1]
```diff
@@ -109,6 +109,11 @@ func (pkg ZarfPackage) UniqueNamespaceCount() int {
 		for _, manifest := range component.Manifests {
 			uniqueNamespaces[manifest.Namespace] = struct{}{}
 		}
+		for _, action := range component.Actions.GetAll() {
+			if action.Wait != nil && action.Wait.Cluster != nil && action.Wait.Cluster.Namespace != "" {
+				uniqueNamespaces[action.Wait.Cluster.Namespace] = struct{}{}
+			}
+		}
```
Comment (AustinAbro321) [inline src/api/v1alpha1/package.go]: I don't think wait namespaces should count as unique namespaces. I think we should update the namespace when it matches the original package namespace, but not count the package as having multiple namespaces when the wait condition has a new namespace.  

I'm picturing a package that can be deployed into any namespace, but it has to check for the existence of a different resource before it deploys, maybe flux-system. We don't want to mutate that namespace check, but we would want that package deployable anywhere.

Comment (brandtkeller) [reply src/api/v1alpha1/package.go]: That is a great point and I don't have any hard opinions against that option - let me give that a run.

Comment (brandtkeller) [reply src/api/v1alpha1/package.go]: quick prototype - the only downside here is that the original solution did not need to be namespace aware. The associated methods for updating namespaces do so without any awareness of the previous value. In order to support this we need to determine the namespace we want to overwrite. 

I'm going to pose some slightly duplicative logic for sake of feeling this out further.

File: src/api/v1alpha1/package.go [hunk 2]
```diff
@@ -113,7 +115,21 @@ func (pkg ZarfPackage) UniqueNamespaceCount() int {
...
+			uniqueNamespaces[chart.Namespace] = struct{}{}
+		}
+		for _, manifest := range component.Manifests {
+			uniqueNamespaces[manifest.Namespace] = struct{}{}
+		}
+	}
+	return slices.Collect(maps.Keys(uniqueNamespaces))
+}
+
+// UpdateAllComponentNamespaces updates all existing chart/manifest namespaces to the provided one
```
Comment (AustinAbro321) [inline src/api/v1alpha1/package.go]: Given that we're taking the stance that it's a bug that wait actions are not updated. I'd be in favor of either removing it or adding "original" as a parameter instead of a separate "UpdateAllComponentNamespacesByName". 

Another option to avoid a breaking change would to deprecate this function and point to UpdateAllComponentNamespacesByName

File: src/api/v1alpha1/package.go [hunk 3]
```diff
@@ -126,6 +142,25 @@ func (pkg ZarfPackage) UpdateAllComponentNamespaces(namespace string) {
 	}
 }
 
+// UpdateAllComponentNamespacesByName updates all matching namespaces to the provided one
+func (pkg ZarfPackage) UpdateAllComponentNamespacesByName(original, target string) {
```
Comment (AustinAbro321) [inline src/api/v1alpha1/package.go]: I feel that pkg/packager may be a better place for this function. We're de-coupling the function from the logic of namespace overrides. For instance, charts or manifest namespaces won't be updated if they don't equal the original. In practice this won't ever happen, though I can see why this might be added to this function given that it's in the data layer. 

Still, this feels like a code smell to me, I think we might be better served by moving this function to the logic layer (pkg/packager), given that it's use case is tightly coupled to the namespace overrides logic. Having the function at this layer will also reduce duplication as we introduce new API versions.

Comment (AustinAbro321) [reply src/api/v1alpha1/package.go]: @brandtkeller curious on your thoughts here. I don't think there's a flow where we'd want to encourage users to run this function outside of deploy with namespace overrides set. For instance, an SDK user, might see this function, call it on their package, then call `packager.Deploy` without setting namespace overrides. In this case, they'd miss the validation, and the secret features of namespace overrides.  

Ultimately, I think it's best to keep the schema object as a pure data object, instead of also having functions that mutate it. Looking through this and `UpdateAllComponentNamespaces` are the only mutating functions.  I feel that mutations will be better served being near the surrounding logic for their mutation.

Comment (brandtkeller) [reply src/api/v1alpha1/package.go]: You make a good point - I need to revisit the model overall. I had some hesitations about moving mutation outside of the data object with regards to potential deviations across schemas. Let me consider further.

File: src/api/v1alpha1/package.go [hunk 4]
```diff
@@ -101,29 +103,25 @@ func (pkg ZarfPackage) IsSBOMAble() bool {
...
+	return len(pkg.UniqueNamespaces())
+}
+
+// UniqueNamespaces returns a slice of all unique namespaces in the package
+func (pkg ZarfPackage) UniqueNamespaces() []string {
 	uniqueNamespaces := make(map[string]struct{})
 	for _, component := range pkg.Components {
 		for _, chart := range component.Charts {
-			uniqueNamespaces[chart.Namespace] = struct{}{}
+			if chart.Namespace != "" {
```
Comment (brandtkeller) [inline src/api/v1alpha1/package.go]: note: given a package with one distinct namespace defined and then other undefined namespaces on a chart or manifest - we will not update elements with empty namespaces to the new target namespace (at least how this is currently). Worth considering this edge case and whether we want to update empty to the target.

File: src/pkg/packager/packager.go [hunk 5]
```diff
@@ -86,17 +86,57 @@ func generateValuesOverrides(_ context.Context, chart v1alpha1.ZarfChart, compon
 }
 
 // OverridePackageNamespace overrides the package namespace if the package contains only one unique namespace
-func OverridePackageNamespace(pkg v1alpha1.ZarfPackage, namespace string) error {
+func OverridePackageNamespace(pkg *v1alpha1.ZarfPackage, namespace string) error {
```
Comment (brandtkeller) [inline src/pkg/packager/packager.go:89]: I think it might be worth updating this signature (as is currently proposed). It is currently working as expected because the struct fields are slices (which share their backing arrays). Making this behavior explicit leaves us less likely to continue the pattern.

File: src/api/v1alpha1/package.go (hunk 3 above)
Comment (brandtkeller) [reply src/api/v1alpha1/package.go]: Updated.

File: src/api/v1alpha1/package.go (hunk 4 above)
Comment (AustinAbro321) [reply src/api/v1alpha1/package.go]: Having one namespace defined and one namespace empty blocks namespace overrides, but this PR starts to allow that. Is this intentional? I'd lean towards keeping all namespaces as the same a strict requirement including empty, but maybe there is a use case I'm not thinking of. 

You cannot have an empty namespace on charts because of validation, but you can have an empty namespace for manifests

File: src/pkg/packager/packager.go (hunk 5 above)
Comment (AustinAbro321) [reply src/pkg/packager/packager.go:89]: Agreed, you'll also want to change this on the other mutation functions `overrideActionSetWaitNamespaces`

File: src/api/v1alpha1/package.go (hunk 4 above)
Comment (brandtkeller) [reply src/api/v1alpha1/package.go]: Yes intentional, I see two distinct paths for opinionation here and both have pros/cons. 

If we treat empty namespace (which is permitted across the zarf manifest) as a distinct/singular namespace in the namespace count - then the override rule is more straight-forward and blocks the empty/defined scenario you mentioned. 

If we ignore empty then we have a slightly less strict stance but potentially more optionality. I have concerns about cluster-scoped resources that won't have a namespace and thus a package (say an operator) that reads those objects (and contains them in the package) would be blocked from the use of overrides.

Comment (AustinAbro321) [reply src/api/v1alpha1/package.go]: To me, the main reason to avoid specifying the namespace are: 
- if your manifests have explicit differing namespaces, so specifying namespace doesn't have an effect
- If you only have cluster scoped resources where a namespace is misleading.

These would not work with namespace overrides as you'd have duplicate resources across packages. Barring a solid use case, I'd prefer to keep empty namespaces in the distinct namespace count. I feel that changing this is scope creep for this PR also.

Comment (brandtkeller) [reply src/api/v1alpha1/package.go]: I think exposing the change in behavior is appropriate to considering this out of scope. I have concerns about what this will mean for cluster scoped resources but the use case is built more on assumptions. Let me revert this behavior.

File: src/pkg/packager/packager.go (hunk 5 above)
Comment (brandtkeller) [reply src/pkg/packager/packager.go:89]: good call - updated
