### PR TITLE
fix: remove correct components from state when  `--components` flag is used

### LINKED ISSUE #4146: Zarf package remove removes the latest component from state even when a different component is chosen
Zarf package remove always removes the latest component from state, even when a different component is chosen. 
### Environment
App version: v0.61.0

### Steps to reproduce
1. create and deploy a package with two components like this
```yaml
kind: ZarfPackageConfig
metadata:
  name: reproduce-remove-bug
components:
  - name: first-component
    required: true
    manifests:
      - name: simple-manifest
        namespace: namespace
        files:
          - simple-pod.yaml
    images:
      - busybox:1.35      

  - name: second-component
    required: true
    charts:
      - name: test-chart1
        version: 6.4.0
        namespace: test-namespace-1
        url: oci://ghcr.io/stefanprodan/charts/podinfo
    images:
      - ghcr.io/stefanprodan/podinfo:6.4.0
```
2. deploy the package
3. remove the package with `zarf package remove zarf-package-reproduce-remove-bug-amd64.tar.zst  --components=first-component --confirm`

### Expected result

State correctly reflects which component was removed.

### Actual Result

The last component in the package is removed

### Visual Proof (screenshots, videos, text, etc)

Image

### Severity/Priority

Critical

### PR DESCRIPTION
**Pull request by AustinAbro321**
## Related Issue

Fixes #4146, #4145

New e2e test only takes ~ 2 seconds

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/test/e2e/41_remove_test.go [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+import (
+	"fmt"
+	"path/filepath"
+	"testing"
+
+	"github.com/stretchr/testify/require"
+	"github.com/zarf-dev/zarf/src/pkg/cluster"
+)
+
+func TestRemovePackage(t *testing.T) {
```
Comment (mkcp) [inline src/test/e2e/41_remove_test.go]: Nit: clarify scope of test

```suggestion
func TestRemovePackageComponents(t *testing.T) {
```

File: src/test/e2e/41_remove_test.go [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+
+	// Create the test package
+	stdOut, stdErr, err := e2e.Zarf(t, "package", "create", testCreate, "-o", tmpdir, "--confirm")
+	require.NoError(t, err, stdOut, stdErr)
+
+	// Deploy the package
+	stdOut, stdErr, err = e2e.Zarf(t, "package", "deploy", packagePath, "--confirm")
+	require.NoError(t, err, stdOut, stdErr)
+
+	// Remove the package and check that the other component is still in state
```
Comment (mkcp) [inline src/test/e2e/41_remove_test.go]: Nit: clarify comment

```suggestion
	// Remove the component "first" and check that the other component is still in state
```

File: src/pkg/packager/load.go [hunk 3]
```diff
@@ -191,6 +191,9 @@ func identifySource(src string) (string, error) {
 
 // GetPackageFromSourceOrCluster retrieves a Zarf package from a source or cluster.
 func GetPackageFromSourceOrCluster(ctx context.Context, cluster *cluster.Cluster, src string, namespaceOverride string, opts LoadOptions) (_ v1alpha1.ZarfPackage, err error) {
+	if opts.Filter == nil {
```
Comment (mkcp) [inline src/pkg/packager/load.go:194]: ++ input verification

File: src/pkg/packager/load.go [hunk 4]
```diff
@@ -203,6 +206,10 @@ func GetPackageFromSourceOrCluster(ctx context.Context, cluster *cluster.Cluster
 		if err != nil {
 			return v1alpha1.ZarfPackage{}, err
 		}
+		depPkg.Data.Components, err = opts.Filter.Apply(depPkg.Data)
```
Comment (mkcp) [inline src/pkg/packager/load.go:209]: Glad the fix was straightforward. Easy to miss though!
