### PR TITLE
fix(injector): improve node resources availability for injector

### LINKED ISSUE #4218: Zarf Injector not calculating node resources correctly
### Environment

zarf version: 0.62.0
Kubernetes distro being used: EKS

### Issue
Currently the Zarf injector does a check to verify there is enough space on the node before deploying the injector pod. The issue in the current logic is that it utilizes "Allocatable CPU" to verify if there is enough space. Allocatable CPU doesn't include the pods running on the node. Instead it is the actual resources minus kube-reserved, system-reserved, and eviction-threshold. This means that the Zarf injector can be scheduled on a node without sufficient resources leading to a failed deployment

[Node Allocatable docs](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#node-allocatable)

Current logic:
```
		if nodeDetails.Status.Allocatable.Cpu().Cmp(minNodeCPU) < 0 ||
		   nodeDetails.Status.Allocatable.Memory().Cmp(minNodeMemory) < 0 {
			continue findImages
		}
```


### Visual Proof (screenshots, videos, text, etc)
```
│ Labels:           app=zarf-injector                                                                                                                                                                                                                                              │
│                   zarf.dev/agent=ignore                                                                                                                                                                                                                                          │
│ Annotations:      <none>                                                                                                                                                                                                                                                         │
│ Status:           Failed                                                                                                                                                                                                                                                         │
│ Reason:           OutOfcpu                                                                                                                                                                                                                                                       │
│ Message:          Pod was rejected: Node didn't have enough resource: cpu, requested: 500, used: 3430, capacity: 3920                                                                                                                                                            │
│ SeccompProfile:   RuntimeDefault        
```
### Severity/Priority
high

### PR DESCRIPTION
**Pull request by brandtkeller**
## Description

This introduces an additional iteration through node pods in order to get an accurate calculation for available resources. This provides a more accurate representation of resources available on a node - as the injector skips the scheduler - which would normally provide this information. 

## Related Issue

Fixes #4218

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/pkg/cluster/injector.go [hunk 1]
```diff
@@ -262,37 +263,69 @@ func (c *Cluster) getInjectorImageAndNode(ctx context.Context, resReq *v1ac.Reso
...
 		nodeDetails, err := c.Clientset.CoreV1().Nodes().Get(ctx, pod.Spec.NodeName, metav1.GetOptions{})
 		if err != nil {
 			return "", "", err
 		}
-		if nodeDetails.Status.Allocatable.Cpu().Cmp(*resReq.Requests.Cpu()) < 0 ||
-			nodeDetails.Status.Allocatable.Memory().Cmp(*resReq.Requests.Memory()) < 0 {
+
+		l.Debug("calculating available resources", "node", nodeDetails.Name)
+		var usedCPU, usedMem int64
+		for _, npod := range podList.Items {
```
Comment (AustinAbro321) [inline src/pkg/cluster/injector.go]: We can't use this podList, we have to get a new podlist from pods on the node. Or rather start by going through nodes and getting the pods on them.

File: src/pkg/cluster/injector.go [hunk 2]
```diff
@@ -262,37 +263,69 @@ func (c *Cluster) getInjectorImageAndNode(ctx context.Context, resReq *v1ac.Reso
...
+				usedMem += ctn.Resources.Requests.Memory().Value()
+			}
+			for _, ctn := range npod.Spec.InitContainers {
+				usedCPU += ctn.Resources.Requests.Cpu().MilliValue()
+				usedMem += ctn.Resources.Requests.Memory().Value()
+			}
+		}
+
+		availCPU := nodeDetails.Status.Allocatable.Cpu().MilliValue() - usedCPU
+		availMem := nodeDetails.Status.Allocatable.Memory().Value() - usedMem
```
Comment (AustinAbro321) [inline src/pkg/cluster/injector.go]: I'd like to see us use the builtin functions for these types. For example, we could do this add have access to Add(), Sub(), and Cmp()

```go
		availableCPU := nodeDetails.Status.Allocatable.Cpu().DeepCopy()
```

File: src/pkg/cluster/injector.go [hunk 3]
```diff
@@ -262,37 +263,69 @@ func (c *Cluster) getInjectorImageAndNode(ctx context.Context, resReq *v1ac.Reso
...
+				continue
+			}
+			for _, ctn := range npod.Spec.Containers {
+				usedCPU += ctn.Resources.Requests.Cpu().MilliValue()
+				usedMem += ctn.Resources.Requests.Memory().Value()
+			}
+			for _, ctn := range npod.Spec.InitContainers {
+				usedCPU += ctn.Resources.Requests.Cpu().MilliValue()
+				usedMem += ctn.Resources.Requests.Memory().Value()
+			}
```
Comment (AustinAbro321) [inline src/pkg/cluster/injector.go]: Should we check emphemeral containers as well?

File: src/pkg/cluster/injector.go [hunk 4]
```diff
@@ -250,6 +250,7 @@ func (c *Cluster) createPayloadConfigMaps(ctx context.Context, tmpDir, imagesDir
 
 // getImagesAndNodesForInjection checks for images on schedulable nodes within a cluster.
 func (c *Cluster) getInjectorImageAndNode(ctx context.Context, resReq *v1ac.ResourceRequirementsApplyConfiguration) (string, string, error) {
```
Comment (AustinAbro321) [inline src/pkg/cluster/injector.go:253]: With the extra complexity this introduces, I think it'd be worth creating a unit test for this function

File: src/pkg/cluster/injector.go (hunk 1 above)
Comment (brandtkeller) [reply src/pkg/cluster/injector.go]: I believe we accomplish the task by isolating by a node in the following lines - but there is a tradeoff here for efficiency. 

I did update the logic to optimize:
- get all nodes and all pods
- map pods by node

Iterate through nodes and process pods by node for available resources - continue early when possible.

File: src/pkg/cluster/injector.go (hunk 3 above)
Comment (brandtkeller) [reply src/pkg/cluster/injector.go]: good catch

File: src/pkg/cluster/injector.go (hunk 2 above)
Comment (brandtkeller) [reply src/pkg/cluster/injector.go]: Ah! great catch - I passed over those on `resource.Quantity` type initially - should be using them properly now.

File: src/pkg/cluster/injector.go (hunk 4 above)
Comment (brandtkeller) [reply src/pkg/cluster/injector.go:253]: Add multiple tests for successful and failing paths

File: src/pkg/cluster/injector.go [hunk 5]
```diff
@@ -250,49 +250,102 @@ func (c *Cluster) createPayloadConfigMaps(ctx context.Context, tmpDir, imagesDir
...
+
+		if candidateImage != "" {
+			l.Debug("selected image for injector", "node", node.Name, "image", candidateImage)
+			return candidateImage, node.Name, nil
+		}
+
+		l.Debug("no suitable image found on node", "node", node.Name)
 	}
+
+	l.Debug("failed to find suitable injector image or node")
```
Comment (AustinAbro321) [inline src/pkg/cluster/injector.go]: nit this is mostly a repeat of the error message

**Review by AustinAbro321 — APPROVED** [review]
LGTM

File: src/pkg/cluster/injector.go (hunk 5 above)
Comment (brandtkeller) [reply src/pkg/cluster/injector.go]: Agreed! Same wavelength - this was removed in [this commit](https://github.com/zarf-dev/zarf/pull/4220/commits/8ada1fc90b918dfa57193a6627d02eca24876792)
