### PR TITLE
fix(cache): support for default sdk cache path

### LINKED ISSUE #4764: SDK Default Cache Path Resolution
### Describe what should be investigated or refactored

Zarf's src/pkg/packager package exposes public functions (Create, LoadPackage, DevDeploy, Pull, FindImages, PublishSkeleton, Publish, Lint, Inspect) that each accept a CachePath string in their options. Today, every one of these functions passes CachePath directly to downstream consumers — images.Pull, zoci.GetOCICacheModifier, createImageSBOM, helm chart packaging — all of which assume the path is set and the directory exists.

This works for the CLI because getCachePath in src/cmd/cmd.go always resolves a path before calling into the library. But the library layer itself has no safety net. An SDK consumer who omits CachePath (the zero value "") hits failures deep in the call stack: zoci.GetOCICacheModifier tries to open ""/images as an OCI store, images.Pull calls helpers.CreateDirectory(""), and stereoscope's layer cache writes to a path that doesn't exist.

This matters because Zarf is actively being adopted as a library. The src/pkg/packager functions are the public API surface, and every one of them has an undocumented requirement that CachePath must be non-empty and point to a valid location. SDK consumers have no way to discover this except by hitting runtime errors. The cache is also not truly optional — it's wired into OCI pulls (orasCache.New wraps every remote registry fetch), SBOM generation (stereoscope uses it for uncompressed layer storage), and helm chart operations.

### PR DESCRIPTION
**Pull request by brandtkeller**
## Description

Zarf's public `src/pkg/packager/` functions all accept a `CachePath` string in their options. The CLI always sets this via `getCachePath()`, but SDK consumers who omit it get an empty string that causes failures deep in the call stack (`zoci.GetOCICacheModifier`, `images.Pull`, `createImageSBOM`, helm operations). This change adds a `GetCachePath` utility and applies it at every public entry point so SDK consumers get a working default (`os.UserCacheDir()/zarf`) without needing CLI knowledge. 

CLI behavior is unchanged — the CLI always passes an explicit path but worth acknowledging optionality here to change the CLI to support #3828 .

There is some redundancy across some transient load operations where this is called multiple times. Given the cases all are subsequently public functions and the operation is idempotent I think this is reasonable. 

## Related Issue

Fixes #4764

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

**Comment by AustinAbro321** [comment]
@brandtkeller I am curious what your thoughts are on allowing users not to cache resources at all, there are some blockers here, see #3774. Right now Zarf assumes and relies on a cachepath existing in some spots, but there should be a future state where a user could preform operations without a cache at all. 

I think there are two paths for this: 
1. `--no-cache` flag / option, this would work with this PR
2. An empty cachepath to SDK calls or explicitly setting --zarf-cache="" would allow for no cache usage.

I think option 1 is a good approach. Wanted to get your thoughts on this first, then I can update #3774 with the decision.

**Comment by brandtkeller** [comment]
> I am curious what your thoughts are on allowing users not to cache resources at all, there are some blockers here, see #3774. Right now Zarf assumes and relies on a cachepath existing in some spots, but there should be a future state where a user could preform operations without a cache at all.
> 
> I think there are two paths for this:
> 
> 1. `--no-cache` flag / option, this would work with this PR
> 2. An empty cachepath to SDK calls or explicitly setting --zarf-cache="" would allow for no cache usage.
> 
> I think option 1 is a good approach. Wanted to get your thoughts on this first, then I can update #3774 with the decision.

I'm in the same boat. I thought about this originally and decided there were a few constraints (as I understood them) where even a temporary cache is strictly required (I believe Helm errors and syft has a requirement) - but to where we could introduce an additional option that would essentially make the tempDir ephemeral per-cache-required function call.

File: src/pkg/utils/io.go [hunk 1]
```diff
@@ -17,6 +17,19 @@ const (
 	tmpPathPrefix = "zarf-"
 )
 
+// ResolveCachePath returns cachePath if non-empty, otherwise falls back to
+// filepath.Join(os.UserCacheDir(), "zarf") which respects XDG_CACHE_HOME on Linux.
+func ResolveCachePath(cachePath string) (string, error) {
+	if cachePath != "" {
+		return cachePath, nil
+	}
+	cacheDir, err := os.UserCacheDir()
```
Comment (AustinAbro321) [inline src/pkg/utils/io.go:26]: Curious what your thoughts are for the future default of the CLI? Do we see it changing to also `ResolveCachePath` maybe in v1.0 or will it always stay as `~/.zarf-cache`? 

One strategy we could use would be to create function similar to `os.UserCacheDir`, but only return a value when environment variables are set. Otherwise we would keep a default of `~/.zarf-cache` for consistency through the CLI and SDK.

PR looks good otherwise.

Comment (brandtkeller) [reply src/pkg/utils/io.go:26]: That is definitely the question... My vote is to move towards `ResolveCachePath` in the CLI in `v1.0` so that CLI and SDK align and we can further evaluate the requirements of using the `config` package.

Comment (AustinAbro321) [reply src/pkg/utils/io.go:26]: Seems like a good path to me as well.

One way to handle tasks like this, without introducing PRs that need to be worked right before we hit v1.0, would to add a feature flag, `--new-cache-home`, that we keep disabled until v1.0.

Comment (brandtkeller) [reply src/pkg/utils/io.go:26]: That is a great callout - I'll link this to the outsanding issue
