### PR TITLE
fix(create): built package path separators

### LINKED ISSUE #3275: Zarf package output file path separators
### Environment
Device and OS: Linux and Windows
App version: v0.43.0
Kubernetes distro being used: N/A
Other: N/A

### Steps to reproduce

1. Build Zarf package on a Linux machine.
2. Build Zarf package on a Windows machine.
3. Compare zarf.yaml in the two different Zarf packages.

### Expected result

I expect the content apart from the build field to be identical.

### Actual Result

File paths in the zarf.yaml differ due to different file separators. These should be the same.

### Visual Proof (screenshots, videos, text, etc)

N/A

### Severity/Priority

Low

### Additional Context

This does not have any functional impact on Zarf as we currently normalize the separators in runtime,

### PR DESCRIPTION
**Pull request by brandtkeller**
## Description

I bumped this issue in priority after realizing the implications. 

Built Zarf packages should be byte-identical across operating systems, but filepath.Join was producing OS-native separators in path strings that get serialized into the published zarf package.

This really only impacts import/skeletons and how paths are resolved to my knowledge. Worth doing now as a pattern before we introduce any new import/component behaviors. 

This statically defines checksums in testing which can be a burden during development when the package shape changes but a worthwhile tradeoff for reproducibility. 

## Related Issue

Fixes #3275 

Relates to #

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/test/testutil/paths.go [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+				check(prefix+".manifests["+strconv.Itoa(mi)+"].files["+strconv.Itoa(fi)+"]", f)
+			}
+			for ki, k := range m.Kustomizations {
+				check(prefix+".manifests["+strconv.Itoa(mi)+"].kustomizations["+strconv.Itoa(ki)+"]", k)
+			}
+		}
+		for di, d := range comp.DataInjections {
+			check(prefix+".dataInjections["+strconv.Itoa(di)+"].source", d.Source)
+		}
+		actionsByName := map[string][]v1alpha1.ZarfComponentAction{
```
Comment (AustinAbro321) [inline src/test/testutil/paths.go:67]: I wasn't sure if this would cause a bug since windows users still use these paths, but it looks like windows is okay with a forward slash as a separator

**Review by AustinAbro321 — APPROVED** [review]
LGTM
