### PR TITLE
fix(archive): cleanup the archive package

### LINKED ISSUE #3821: Archives cleanup
### Describe what should be investigated or refactored
Following #3788 there is still some room for improvement with the archive implementation. This issue captures remaining work. 

- De-duplicating logic in the `archive` package
- evaluating use of context
- parallel testing

### PR DESCRIPTION
**Pull request by brandtkeller**
## Description

Goal of this Pull Request was to cleanup and deduplicate the `archive` package logic while applying patterns that help make the package more clean. 

- Generation of the archivers map moved to a function to reduce nearly identical literals being defined over and over
- Pull out the common "open and identify" logic using the `withArchive` helper such that extraction functions can share it.
- file-writing handlers (defaultHandler, stripHandler, filterHandler) to avoid copy-pasting the same os.MkdirAll/OpenFile/io.Copy logic.

Added an `e2e` test to cover expectations for a zarf package being decompressed such that we can identify any regressions in the package decompressed directory structure. 

Test coverage improved ~%15 with updates/reductions to the code paths. 

## Related Issue

Fixes #3821

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/pkg/archive/archive.go [hunk 1]
```diff
@@ -152,182 +112,194 @@ func Decompress(ctx context.Context, sourceArchive, dst string, opts DecompressO
...
+			if !found[name] {
+				return fmt.Errorf("file %q not found in archive %q", name, src)
+			}
 		}
 	}
 	return nil
 }
 
+// writeFile encapsulates file writing and copying.
+func writeFile(target string, fi archives.FileInfo, flags int) (err error) {
```
Comment (mkcp) [inline src/pkg/archive/archive.go:279]: 👍

File: src/pkg/archive/archive.go [hunk 2]
```diff
@@ -152,182 +112,194 @@ func Decompress(ctx context.Context, sourceArchive, dst string, opts DecompressO
...
-			}
-			defer func() {
-				err = errors.Join(err, in.Close())
-			}()
-
-			if _, err := io.Copy(out, in); err != nil {
-				return err
-			}
-			return nil
+			return writeFile(target, fi, flags)
```
Comment (mkcp) [inline src/pkg/archive/archive.go:214]: ++

**Review by mkcp — DISMISSED** [review]
LGTM

**Review by mkcp — APPROVED** [review]
LGTM
